from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from pathlib import Path
from typing import Any, Protocol


REPO_ROOT = Path(__file__).resolve().parents[2]
BUILD_DIR = REPO_ROOT / "build" / "youtube-podcast"
DEEPDIVE_BUILD_DIR = REPO_ROOT / "build" / "youtube-podcast-deepdive"
LOCAL_STATE_DIR = Path(os.environ.get("NEWS_GRASP_LOCAL_STATE_DIR") or (Path.home() / ".news-grasp"))
SECRETS_PATH = LOCAL_STATE_DIR / "youtube-podcast-secrets.json"
STATE_PATH = LOCAL_STATE_DIR / "youtube-podcast-state.json"
DEFAULT_PLAYLIST_TITLE = "News-Grasp"
DEFAULT_PLAYLIST_DESCRIPTION = "News-Grasp Daily News Briefing の公開ポッドキャストアーカイブ。"
DEEPDIVE_PLAYLIST_TITLE = "News-Grasp DeepDive"
DEEPDIVE_PLAYLIST_DESCRIPTION = "News-Grasp DeepDive 解説対談の公開ポッドキャストアーカイブ。"
_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
_URL_RE = re.compile(r"https?://[^\s)>\"]+")


class PodcastClient(Protocol):
    def ensure_playlist(self, kind: str = "daily") -> str: ...
    def upload_video(self, mp4_path: Path, metadata: dict[str, Any], *, privacy_status: str) -> str: ...
    def update_video_privacy(self, *, video_id: str, privacy_status: str) -> dict[str, Any]: ...
    def add_video_to_playlist(self, *, video_id: str, playlist_id: str) -> str: ...


def _warn(message: str) -> None:
    print(f"[youtube-podcast][WARN] {message}", file=sys.stderr)


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def _load_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8-sig"))
    except json.JSONDecodeError:
        return {}


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    if path.exists():
        path.with_suffix(path.suffix + ".bak").write_text(path.read_text(encoding="utf-8-sig"), encoding="utf-8")
    tmp.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8", newline="\n")
    tmp.replace(path)


def _build_dir(kind: str = "daily") -> Path:
    if kind == "daily":
        return BUILD_DIR
    if kind == "deepdive":
        return DEEPDIVE_BUILD_DIR
    raise ValueError(f"invalid podcast kind: {kind}")


def _uploads_json(kind: str = "daily") -> Path:
    return _build_dir(kind) / "uploads.json"


def _state_path(kind: str = "daily") -> Path:
    suffix = "" if kind == "daily" else "-deepdive"
    return LOCAL_STATE_DIR / f"youtube-podcast{suffix}-state.json"


def _clean_script_text(text: str) -> str:
    lines: list[str] = []
    in_frontmatter = False
    for raw in text.splitlines():
        line = raw.strip()
        if line == "---":
            in_frontmatter = not in_frontmatter
            continue
        if in_frontmatter or not line or line.startswith("#") or line.startswith("```"):
            continue
        if line.startswith("type:") or line.startswith("date:"):
            continue
        lines.append(line)
    return "\n".join(lines).strip()


def _deepdive_frontmatter(day: str) -> dict[str, str]:
    md_path = REPO_ROOT / "digest" / "DeepDive" / f"{day}-DeepDive.md"
    if not md_path.exists():
        return {}
    text = md_path.read_text(encoding="utf-8-sig", errors="replace")
    if not text.startswith("---"):
        return {}
    _, _, rest = text.partition("---")
    fm_text, _, _body = rest.partition("---")
    data: dict[str, str] = {}
    for raw in fm_text.splitlines():
        if ":" not in raw:
            continue
        key, _, value = raw.partition(":")
        value = value.strip().strip('"').strip("'")
        if value:
            data[key.strip()] = value
    return data


def build_metadata(day: str, *, kind: str = "daily") -> dict[str, Any]:
    if kind == "deepdive":
        fm = _deepdive_frontmatter(day)
        title = str(fm.get("title") or "News-Grasp DeepDive")
        theme = str(fm.get("theme") or "News-Grasp DeepDive の解説対談です。")
        description_parts = [
            f"News-Grasp DeepDive Dialogue {day}",
            "",
            title,
            "",
            theme,
            "",
            "この動画は News-Grasp DeepDive の解説対談音声を YouTube Podcast 用に静止画動画化したものです。",
            "若手社員の質問に先輩社員が答える形で、DeepDive の背景・用語・論点を会話で振り返ります。",
            "",
            "Generated by News-Grasp.",
        ]
        return {
            "title": f"News-Grasp DeepDive Dialogue {day}",
            "description": "\n".join(description_parts),
            "tags": ["News-Grasp", "DeepDive", "解説対談", "Podcast", "ビジネスニュース"],
            "categoryId": "25",
        }
    if kind != "daily":
        raise ValueError(f"invalid podcast kind: {kind}")
    script = REPO_ROOT / "digest" / "Summary" / f"{day}-audio-script.md"
    body = _clean_script_text(script.read_text(encoding="utf-8-sig", errors="replace")) if script.exists() else ""
    links = sorted(set(_URL_RE.findall(body)))
    overview = body.splitlines()[0] if body else "News-Grasp の日次ニュース朗読です。"
    if len(overview) > 240:
        overview = overview[:237] + "..."
    description_parts = [
        f"News-Grasp Daily News Briefing {day}",
        "",
        overview,
        "",
        "この動画は News-Grasp の日次 TTS 音声を YouTube Podcast 用に静止画動画化したものです。",
    ]
    if links:
        description_parts.extend(["", "出典・参照リンク:", *links[:20]])
    description_parts.extend(["", "Generated by News-Grasp."])
    return {
        "title": f"News-Grasp Daily News Briefing {day}",
        "description": "\n".join(description_parts),
        "tags": ["News-Grasp", "ニュース", "Daily News", "Podcast", "AIニュース"],
        "categoryId": "25",
    }


def _build_metadata(day: str, kind: str) -> dict[str, Any]:
    try:
        return build_metadata(day, kind=kind)
    except TypeError:
        # 既存テストや簡易 monkeypatch は build_metadata(day) 形式。
        return build_metadata(day)


def _load_uploads(kind: str = "daily") -> dict[str, Any]:
    return _load_json(_uploads_json(kind))


def _write_uploads(payload: dict[str, Any], kind: str = "daily") -> None:
    _write_json(_uploads_json(kind), payload)


def _already_public(day: str, mp4_hash: str, kind: str = "daily") -> dict[str, Any] | None:
    row = _load_uploads(kind).get(day)
    if not isinstance(row, dict):
        return None
    if row.get("status") == "public" and row.get("mp4_sha256") == mp4_hash:
        return row
    return None


def _ensure_playlist(client: PodcastClient, kind: str) -> str:
    try:
        return client.ensure_playlist(kind)
    except TypeError:
        # 既存テストや簡易FakeClientは引数なし ensure_playlist を実装している。
        return client.ensure_playlist()


def _ensure_primary_podcast_membership(
    row: dict[str, Any],
    *,
    client: PodcastClient,
    video_id: str,
    kind: str,
) -> None:
    if kind != "deepdive":
        return
    primary_playlist_id = str(row.get("primaryPodcastPlaylistId") or _ensure_playlist(client, "daily"))
    current_playlist_id = str(row.get("playlistId") or "")
    primary_playlist_item_id = str(row.get("primaryPodcastPlaylistItemId") or "")
    if not primary_playlist_item_id:
        if primary_playlist_id == current_playlist_id:
            primary_playlist_item_id = str(row.get("playlistItemId") or "")
        else:
            primary_playlist_item_id = client.add_video_to_playlist(video_id=video_id, playlist_id=primary_playlist_id)
    row["primaryPodcastPlaylistId"] = primary_playlist_id
    row["primaryPodcastPlaylistItemId"] = primary_playlist_item_id


class YouTubePodcastClient:
    def __init__(self, service: Any):
        self.service = service

    @classmethod
    def from_local_secrets(cls, secrets_path: Path = SECRETS_PATH) -> "YouTubePodcastClient":
        secrets = _load_json(secrets_path)
        required = ["client_id", "client_secret", "refresh_token"]
        missing = [key for key in required if not secrets.get(key)]
        if missing:
            raise RuntimeError(f"YouTube OAuth secrets missing: {', '.join(missing)} ({secrets_path})")
        try:
            from google.oauth2.credentials import Credentials
            from googleapiclient.discovery import build
        except ImportError as exc:
            raise RuntimeError("google-api-python-client / google-auth が未導入です。依存関係をインストールしてください。") from exc
        credentials = Credentials(
            token=None,
            refresh_token=str(secrets["refresh_token"]),
            token_uri=str(secrets.get("token_uri") or "https://oauth2.googleapis.com/token"),
            client_id=str(secrets["client_id"]),
            client_secret=str(secrets["client_secret"]),
            scopes=[
                "https://www.googleapis.com/auth/youtube",
                "https://www.googleapis.com/auth/youtube.upload",
            ],
        )
        return cls(build("youtube", "v3", credentials=credentials))

    def ensure_playlist(self, kind: str = "daily") -> str:
        state = _load_json(_state_path(kind))
        playlist_id = str(state.get("playlist_id") or "")
        if playlist_id:
            return playlist_id
        title = DEEPDIVE_PLAYLIST_TITLE if kind == "deepdive" else DEFAULT_PLAYLIST_TITLE
        description = DEEPDIVE_PLAYLIST_DESCRIPTION if kind == "deepdive" else DEFAULT_PLAYLIST_DESCRIPTION
        request = self.service.playlists().insert(
            part="snippet,status",
            body={
                "snippet": {
                    "title": title,
                    "description": description,
                    "defaultLanguage": "ja",
                },
                "status": {"privacyStatus": "public"},
            },
        )
        response = request.execute()
        playlist_id = str(response.get("id") or "")
        if not playlist_id:
            raise RuntimeError("YouTube playlist create response did not include id")
        state["playlist_id"] = playlist_id
        _write_json(_state_path(kind), state)
        return playlist_id

    def upload_video(self, mp4_path: Path, metadata: dict[str, Any], *, privacy_status: str) -> str:
        try:
            from googleapiclient.http import MediaFileUpload
        except ImportError as exc:
            raise RuntimeError("google-api-python-client が未導入です。依存関係をインストールしてください。") from exc
        request = self.service.videos().insert(
            part="snippet,status",
            body={
                "snippet": {
                    "title": metadata["title"],
                    "description": metadata["description"],
                    "tags": metadata.get("tags", []),
                    "categoryId": metadata.get("categoryId", "25"),
                    "defaultLanguage": "ja",
                },
                "status": {
                    "privacyStatus": privacy_status,
                    "embeddable": True,
                    "publicStatsViewable": True,
                    "selfDeclaredMadeForKids": False,
                },
            },
            media_body=MediaFileUpload(str(mp4_path), mimetype="video/mp4", resumable=True),
        )
        response = request.execute()
        video_id = str(response.get("id") or "")
        if not video_id:
            raise RuntimeError("YouTube upload response did not include id")
        return video_id

    def update_video_privacy(self, *, video_id: str, privacy_status: str) -> dict[str, Any]:
        request = self.service.videos().update(
            part="status",
            body={
                "id": video_id,
                "status": {
                    "privacyStatus": privacy_status,
                    "embeddable": True,
                    "publicStatsViewable": True,
                    "selfDeclaredMadeForKids": False,
                },
            },
        )
        response = request.execute()
        return response if isinstance(response, dict) else {"id": video_id}

    def add_video_to_playlist(self, *, video_id: str, playlist_id: str) -> str:
        request = self.service.playlistItems().insert(
            part="snippet",
            body={
                "snippet": {
                    "playlistId": playlist_id,
                    "resourceId": {"kind": "youtube#video", "videoId": video_id},
                }
            },
        )
        response = request.execute()
        return str(response.get("id") or "")


def _mp4_and_hash(day: str, kind: str = "daily") -> tuple[Path, str]:
    if not _DATE_RE.match(day):
        raise ValueError(f"invalid date: {day}")
    mp4 = _build_dir(kind) / f"{day}.mp4"
    if not mp4.exists():
        raise FileNotFoundError(f"mp4 not found: {mp4}")
    return mp4, sha256_file(mp4)


def prepare(
    day: str,
    *,
    client: PodcastClient | None = None,
    dry_run: bool = False,
    kind: str = "daily",
) -> dict[str, Any]:
    mp4, mp4_hash = _mp4_and_hash(day, kind)
    uploads = _load_uploads(kind)
    existing = uploads.get(day)
    if isinstance(existing, dict) and existing.get("mp4_sha256") == mp4_hash and existing.get("videoId"):
        return {"date": day, "skipped": True, **existing}

    metadata = _build_metadata(day, kind)
    if dry_run:
        result = {
            "date": day,
            "dry_run": True,
            "phase": "prepared",
            "status": "private",
            "videoId": "",
            "mp4_path": str(mp4),
            "mp4_sha256": mp4_hash,
            "metadata": metadata,
        }
        print(json.dumps(result, ensure_ascii=False))
        return result

    active_client = client or YouTubePodcastClient.from_local_secrets()
    video_id = active_client.upload_video(mp4, metadata, privacy_status="private")
    uploads[day] = {
        "phase": "prepared",
        "status": "private",
        "videoId": video_id,
        "mp4_sha256": mp4_hash,
        "title": metadata["title"],
    }
    _write_uploads(uploads, kind)
    result = {"date": day, "skipped": False, **uploads[day]}
    print(json.dumps(result, ensure_ascii=False))
    return result


def finalize(day: str, *, client: PodcastClient | None = None, kind: str = "daily") -> dict[str, Any]:
    _mp4_and_hash(day, kind)
    uploads = _load_uploads(kind)
    row = uploads.get(day)
    if not isinstance(row, dict) or not row.get("videoId"):
        raise RuntimeError(f"prepared podcast upload not found for {day}")
    if row.get("status") == "public" and row.get("playlistItemId"):
        return {"date": day, "skipped": True, **row}

    active_client = client or YouTubePodcastClient.from_local_secrets()
    video_id = str(row["videoId"])
    playlist_id = str(row.get("playlistId") or _ensure_playlist(active_client, kind))
    active_client.update_video_privacy(video_id=video_id, privacy_status="public")
    playlist_item_id = str(row.get("playlistItemId") or "")
    if not playlist_item_id:
        playlist_item_id = active_client.add_video_to_playlist(video_id=video_id, playlist_id=playlist_id)
    row.update(
        {
            "phase": "finalized",
            "status": "public",
            "playlistId": playlist_id,
            "playlistItemId": playlist_item_id,
        }
    )
    _ensure_primary_podcast_membership(row, client=active_client, video_id=video_id, kind=kind)
    uploads[day] = row
    _write_uploads(uploads, kind)
    result = {"date": day, "skipped": False, **row}
    print(json.dumps(result, ensure_ascii=False))
    return result


def publish(
    day: str,
    *,
    client: PodcastClient | None = None,
    dry_run: bool = False,
    privacy_status: str = "public",
    kind: str = "daily",
) -> dict[str, Any]:
    mp4, mp4_hash = _mp4_and_hash(day, kind)
    existing = _already_public(day, mp4_hash, kind)
    if existing:
        return {"date": day, "skipped": True, **existing}

    metadata = _build_metadata(day, kind)
    if dry_run:
        result = {
            "date": day,
            "dry_run": True,
            "videoId": "",
            "playlistItemId": "",
            "mp4_path": str(mp4),
            "mp4_sha256": mp4_hash,
            "metadata": metadata,
        }
        print(json.dumps(result, ensure_ascii=False))
        return result

    active_client = client or YouTubePodcastClient.from_local_secrets()
    playlist_id = _ensure_playlist(active_client, kind)
    video_id = active_client.upload_video(mp4, metadata, privacy_status=privacy_status)
    playlist_item_id = active_client.add_video_to_playlist(video_id=video_id, playlist_id=playlist_id)
    row = {
        "status": privacy_status,
        "videoId": video_id,
        "playlistId": playlist_id,
        "playlistItemId": playlist_item_id,
        "mp4_sha256": mp4_hash,
    }
    _ensure_primary_podcast_membership(row, client=active_client, video_id=video_id, kind=kind)
    uploads = _load_uploads(kind)
    uploads[day] = row
    _write_uploads(uploads, kind)
    result = {"date": day, "skipped": False, **uploads[day]}
    print(json.dumps(result, ensure_ascii=False))
    return result


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="YouTube Podcast episode を dry-run または公開 upload します。")
    parser.add_argument("date", help="YYYY-MM-DD")
    parser.add_argument("--kind", choices=["daily", "deepdive"], default="daily", help="daily=日次朗読 / deepdive=DeepDive解説対談")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--prepare", action="store_true", help="push 前に private video として upload する。")
    mode.add_argument("--finalize", action="store_true", help="Web 公開確認後に public 化して playlist に追加する。")
    mode.add_argument("--publish", action="store_true", help="YouTube へ公開 upload して podcast playlist に追加する。")
    parser.add_argument("--dry-run", action="store_true", help="YouTube API を呼ばず mp4 と metadata を検査する。")
    parser.add_argument("--privacy-status", default="public", choices=["public", "private", "unlisted"])
    args = parser.parse_args(argv)
    try:
        if args.prepare:
            prepare(args.date, dry_run=args.dry_run, kind=args.kind)
        elif args.finalize:
            if args.dry_run:
                raise ValueError("--finalize cannot be combined with --dry-run")
            finalize(args.date, kind=args.kind)
        else:
            publish(args.date, dry_run=args.dry_run, privacy_status=args.privacy_status, kind=args.kind)
        return 0
    except Exception as exc:
        _warn(str(exc))
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
