from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from pathlib import Path
from typing import Any, Protocol


REPO_ROOT = Path(__file__).resolve().parents[2]
BUILD_DIR = REPO_ROOT / "build" / "youtube-podcast"
LOCAL_STATE_DIR = Path(os.environ.get("NEWS_GRASP_LOCAL_STATE_DIR") or (Path.home() / ".news-grasp"))
SECRETS_PATH = LOCAL_STATE_DIR / "youtube-podcast-secrets.json"
STATE_PATH = LOCAL_STATE_DIR / "youtube-podcast-state.json"
DEFAULT_PLAYLIST_TITLE = "News-Grasp"
DEFAULT_PLAYLIST_DESCRIPTION = "News-Grasp Daily News Briefing の公開ポッドキャストアーカイブ。"
_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
_URL_RE = re.compile(r"https?://[^\s)>\"]+")


class PodcastClient(Protocol):
    def ensure_playlist(self) -> str: ...
    def upload_video(self, mp4_path: Path, metadata: dict[str, Any], *, privacy_status: str) -> str: ...
    def add_video_to_playlist(self, *, video_id: str, playlist_id: str) -> str: ...


def _warn(message: str) -> None:
    print(f"[youtube-podcast][WARN] {message}", file=sys.stderr)


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def _load_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8-sig"))
    except json.JSONDecodeError:
        return {}


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8", newline="\n")


def _uploads_json() -> Path:
    return BUILD_DIR / "uploads.json"


def _state_path() -> Path:
    return LOCAL_STATE_DIR / "youtube-podcast-state.json"


def _clean_script_text(text: str) -> str:
    lines: list[str] = []
    in_frontmatter = False
    for raw in text.splitlines():
        line = raw.strip()
        if line == "---":
            in_frontmatter = not in_frontmatter
            continue
        if in_frontmatter or not line or line.startswith("#") or line.startswith("```"):
            continue
        if line.startswith("type:") or line.startswith("date:"):
            continue
        lines.append(line)
    return "\n".join(lines).strip()


def build_metadata(day: str) -> dict[str, Any]:
    script = REPO_ROOT / "digest" / "Summary" / f"{day}-audio-script.md"
    body = _clean_script_text(script.read_text(encoding="utf-8-sig", errors="replace")) if script.exists() else ""
    links = sorted(set(_URL_RE.findall(body)))
    overview = body.splitlines()[0] if body else "News-Grasp の日次ニュース朗読です。"
    if len(overview) > 240:
        overview = overview[:237] + "..."
    description_parts = [
        f"News-Grasp Daily News Briefing {day}",
        "",
        overview,
        "",
        "この動画は News-Grasp の日次 TTS 音声を YouTube Podcast 用に静止画動画化したものです。",
    ]
    if links:
        description_parts.extend(["", "出典・参照リンク:", *links[:20]])
    description_parts.extend(["", "Generated by News-Grasp."])
    return {
        "title": f"News-Grasp Daily News Briefing {day}",
        "description": "\n".join(description_parts),
        "tags": ["News-Grasp", "ニュース", "Daily News", "Podcast", "AIニュース"],
        "categoryId": "25",
    }


def _load_uploads() -> dict[str, Any]:
    return _load_json(_uploads_json())


def _write_uploads(payload: dict[str, Any]) -> None:
    _write_json(_uploads_json(), payload)


def _already_public(day: str, mp4_hash: str) -> dict[str, Any] | None:
    row = _load_uploads().get(day)
    if not isinstance(row, dict):
        return None
    if row.get("status") == "public" and row.get("mp4_sha256") == mp4_hash:
        return row
    return None


class YouTubePodcastClient:
    def __init__(self, service: Any):
        self.service = service

    @classmethod
    def from_local_secrets(cls, secrets_path: Path = SECRETS_PATH) -> "YouTubePodcastClient":
        secrets = _load_json(secrets_path)
        required = ["client_id", "client_secret", "refresh_token"]
        missing = [key for key in required if not secrets.get(key)]
        if missing:
            raise RuntimeError(f"YouTube OAuth secrets missing: {', '.join(missing)} ({secrets_path})")
        try:
            from google.oauth2.credentials import Credentials
            from googleapiclient.discovery import build
        except ImportError as exc:
            raise RuntimeError("google-api-python-client / google-auth が未導入です。依存関係をインストールしてください。") from exc
        credentials = Credentials(
            token=None,
            refresh_token=str(secrets["refresh_token"]),
            token_uri=str(secrets.get("token_uri") or "https://oauth2.googleapis.com/token"),
            client_id=str(secrets["client_id"]),
            client_secret=str(secrets["client_secret"]),
            scopes=[
                "https://www.googleapis.com/auth/youtube",
                "https://www.googleapis.com/auth/youtube.upload",
            ],
        )
        return cls(build("youtube", "v3", credentials=credentials))

    def ensure_playlist(self) -> str:
        state = _load_json(_state_path())
        playlist_id = str(state.get("playlist_id") or "")
        if playlist_id:
            return playlist_id
        request = self.service.playlists().insert(
            part="snippet,status",
            body={
                "snippet": {
                    "title": DEFAULT_PLAYLIST_TITLE,
                    "description": DEFAULT_PLAYLIST_DESCRIPTION,
                    "defaultLanguage": "ja",
                },
                "status": {"privacyStatus": "public"},
            },
        )
        response = request.execute()
        playlist_id = str(response.get("id") or "")
        if not playlist_id:
            raise RuntimeError("YouTube playlist create response did not include id")
        state["playlist_id"] = playlist_id
        _write_json(_state_path(), state)
        return playlist_id

    def upload_video(self, mp4_path: Path, metadata: dict[str, Any], *, privacy_status: str) -> str:
        try:
            from googleapiclient.http import MediaFileUpload
        except ImportError as exc:
            raise RuntimeError("google-api-python-client が未導入です。依存関係をインストールしてください。") from exc
        request = self.service.videos().insert(
            part="snippet,status",
            body={
                "snippet": {
                    "title": metadata["title"],
                    "description": metadata["description"],
                    "tags": metadata.get("tags", []),
                    "categoryId": metadata.get("categoryId", "25"),
                    "defaultLanguage": "ja",
                },
                "status": {"privacyStatus": privacy_status, "selfDeclaredMadeForKids": False},
            },
            media_body=MediaFileUpload(str(mp4_path), mimetype="video/mp4", resumable=True),
        )
        response = request.execute()
        video_id = str(response.get("id") or "")
        if not video_id:
            raise RuntimeError("YouTube upload response did not include id")
        return video_id

    def add_video_to_playlist(self, *, video_id: str, playlist_id: str) -> str:
        request = self.service.playlistItems().insert(
            part="snippet",
            body={
                "snippet": {
                    "playlistId": playlist_id,
                    "resourceId": {"kind": "youtube#video", "videoId": video_id},
                }
            },
        )
        response = request.execute()
        return str(response.get("id") or "")


def publish(
    day: str,
    *,
    client: PodcastClient | None = None,
    dry_run: bool = False,
    privacy_status: str = "public",
) -> dict[str, Any]:
    if not _DATE_RE.match(day):
        raise ValueError(f"invalid date: {day}")
    mp4 = BUILD_DIR / f"{day}.mp4"
    if not mp4.exists():
        raise FileNotFoundError(f"mp4 not found: {mp4}")
    mp4_hash = sha256_file(mp4)
    existing = _already_public(day, mp4_hash)
    if existing:
        return {"date": day, "skipped": True, **existing}

    metadata = build_metadata(day)
    if dry_run:
        result = {
            "date": day,
            "dry_run": True,
            "videoId": "",
            "playlistItemId": "",
            "mp4_path": str(mp4),
            "mp4_sha256": mp4_hash,
            "metadata": metadata,
        }
        print(json.dumps(result, ensure_ascii=False))
        return result

    active_client = client or YouTubePodcastClient.from_local_secrets()
    playlist_id = active_client.ensure_playlist()
    video_id = active_client.upload_video(mp4, metadata, privacy_status=privacy_status)
    playlist_item_id = active_client.add_video_to_playlist(video_id=video_id, playlist_id=playlist_id)
    uploads = _load_uploads()
    uploads[day] = {
        "status": privacy_status,
        "videoId": video_id,
        "playlistId": playlist_id,
        "playlistItemId": playlist_item_id,
        "mp4_sha256": mp4_hash,
    }
    _write_uploads(uploads)
    result = {"date": day, "skipped": False, **uploads[day]}
    print(json.dumps(result, ensure_ascii=False))
    return result


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="YouTube Podcast episode を dry-run または公開 upload します。")
    parser.add_argument("date", help="YYYY-MM-DD")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--dry-run", action="store_true", help="YouTube API を呼ばず mp4 と metadata を検査する。")
    mode.add_argument("--publish", action="store_true", help="YouTube へ公開 upload して podcast playlist に追加する。")
    parser.add_argument("--privacy-status", default="public", choices=["public", "private", "unlisted"])
    args = parser.parse_args(argv)
    try:
        publish(args.date, dry_run=args.dry_run, privacy_status=args.privacy_status)
        return 0
    except Exception as exc:
        _warn(str(exc))
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
