"""News Grasp テスト用モックデータ。

設計エクスポート (design/untitled/project/data/news-data-full.js) を Python に
ポートしたサンプル。テンプレートのレイアウト確認や Webhook 経路テストに使う。

5 カテゴリ × 各 5 件（フル 10 件は冗長なので軽量化）。
記事本文は本物っぽい強調記法 [[..]] / __..__ を含む。
"""
from __future__ import annotations

ISSUE_DATE = "2026-04-28"
ISSUE_NO = "20260428"
ISSUE_WEEKDAY = "火"

CATEGORIES = [
    {
        "id": "fx",
        "name": "為替",
        "nameEn": "Foreign Exchange",
        "accent": "#B8860B",
        "glyph": "¥",
        "summary": "円高転換の兆し。日米金利差の縮小観測が支配的で、ヘッジファンド勢のポジション調整が始まった。",
        "items": [
            {"score": 95, "time": "07:42", "source": "Bloomberg Markets",
             "title": "ドル円、151円台前半まで急伸後に反落──FOMC議事要旨で利下げ示唆",
             "url": "https://example.com/fx/1", "thumb": None,
             "bullets": [
                 "NY市場でドル円は一時[[152.10円]]まで上昇したが、FOMC議事要旨で複数メンバーが__年内追加利下げ__に言及していたことが明らかになり、151.20円台まで反落。",
                 "CFTC建玉では[[ヘッジファンドの円ショート]]が3週連続で減少、累計持ち高は前月比△18%となり、ポジション巻き戻しが鮮明になっている。",
                 "テクニカル面では[[151.50円]]が短期サポート、ここを明確に割れば__一気に149円台__を試す展開という見方が市場のコンセンサス。",
             ]},
            {"score": 88, "time": "08:15", "source": "日本経済新聞",
             "title": "日銀総裁、追加利上げの「条件は整いつつある」と発言",
             "url": "https://example.com/fx/2", "thumb": None,
             "bullets": [
                 "植田総裁は参議院財政金融委員会で、賃金と物価の好循環について「[[これまでより確度が高まっている]]」と述べた。",
                 "市場は[[7月会合]]での追加利上げ観測を織り込み始めており、OISインプライドレートは__0.75%へ20bp上昇__。",
                 "為替市場では発言を受けて円買いが優勢、対ドルで一時90銭の急騰。輸出企業の決算想定レート見直しが視野に入る。",
             ]},
            {"score": 82, "time": "06:58", "source": "Reuters FX",
             "title": "ユーロドル、1.09台回復──ECB高官「6月利下げは決定事項ではない」",
             "url": "https://example.com/fx/3", "thumb": None,
             "bullets": [
                 "ECBの[[シュナーベル理事]]がFTのインタビューでサービスインフレの粘着性に言及、6月会合での利下げは「自動的なものではない」と強調。",
                 "ユーロは対ドルで0.6%上昇、対円では165.20円台まで上昇。__独伊スプレッドは縮小__でリスクオン気味の反応。",
                 "ラガルド総裁の慎重姿勢との温度差が市場で意識されており、6月理事会まで複数の高官発言で揺さぶられる展開が予想される。",
             ]},
            {"score": 74, "time": "10:12", "source": "Swissinfo",
             "title": "スイスフラン、対ユーロで0.97台──SNB介入観測でショート巻き戻し",
             "url": "https://example.com/fx/4", "thumb": None,
             "bullets": [
                 "スイス国立銀行が為替市場で[[散発的な介入]]を行ったとの観測が広がり、フランは対主要通貨で全面高。",
                 "__デフレ圧力__への対応として実需も買いに動いた。スイスCPIは3月+1.0%と既にECB目標を下回る。",
                 "介入規模は推計20〜30億フラン規模、SNBバランスシートへの影響は限定的で当面の継続余力はあるとの分析。",
             ]},
            {"score": 60, "time": "13:45", "source": "AFR",
             "title": "豪ドル、CPI鈍化で0.65割れ──RBAの利下げ前倒し観測",
             "url": "https://example.com/fx/5", "thumb": None,
             "bullets": [
                 "豪第1四半期CPIが前年同期比[[+3.4%]]と市場予想を下回り、豪ドルは対米ドルで0.6485まで下落。",
                 "RBAの__早期利下げ観測__が強まり、OISは8月会合での25bp利下げを6割織り込む水準に。",
                 "中国景気との連動性も意識されるなか、資源価格と豪ドルの相関は一時的に弱含み。",
             ]},
        ],
    },
    {
        "id": "ai",
        "name": "AI",
        "nameEn": "Artificial Intelligence",
        "accent": "#2D5BB8",
        "glyph": "◆",
        "summary": "Anthropic / OpenAI の連続リリースで競争激化。マルチクラウド化と本番運用の死の谷が同時に進行。",
        "items": [
            {"score": 96, "time": "07:00", "source": "Anthropic",
             "title": "Anthropic、Claude Opus 4.7 を一般公開──高解像度ビジョンとコーディング性能を強化",
             "url": "https://example.com/ai/1",
             "thumb": "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&q=80",
             "bullets": [
                 "[[Opus 4.7]] が GA。コーディングベンチで前世代比 +6pt、高解像度ビジョンは __OCR 精度 12% 改善__。",
                 "価格は Opus 4.6 と同水準（入力 $5/M、出力 $25/M）。価格性能比が更に改善した形。",
                 "Managed Agents との組み合わせで、長時間自律作業のエンタープライズユースを狙う戦略が鮮明。",
             ]},
            {"score": 92, "time": "08:30", "source": "CNBC",
             "title": "OpenAI、GPT-5.5 を発表──GPT-5.4 から 6 週間での連続リリース",
             "url": "https://example.com/ai/2", "thumb": None,
             "bullets": [
                 "[[GPT-5.5]] 発表、コーディング・データ分析を重点強化。API 提供は 4/24 開始。",
                 "__6 週間での版上げ__ は競争激化の象徴。Anthropic Opus 4.7 と直接競合する位置取り。",
                 "Microsoft の収益シェア廃止と同時期で、商流マルチクラウド化を視野に入れた戦略リリースとも読める。",
             ]},
            {"score": 87, "time": "09:15", "source": "Bloomberg",
             "title": "Microsoft、OpenAI との収益シェア廃止──クラウド競合へのアクセスを解放",
             "url": "https://example.com/ai/3", "thumb": None,
             "bullets": [
                 "MS が [[OpenAI の独占再販権]] を放棄。OpenAI は __AWS / GCP と直接提携可能__ に。",
                 "AI 商流のマルチクラウド化が一気に進む。Azure 一強体制の終焉を市場は織り込み始めた。",
                 "MSFT 株は時間外で 1.3% 下落、AMZN/GOOGL はそれぞれ +2.1%/+1.8%。資金フローが象徴的。",
             ]},
            {"score": 80, "time": "10:00", "source": "Google Blog",
             "title": "Google、Gemini 3.1 Pro 搭載 Deep Research Max を API 公開",
             "url": "https://example.com/ai/4", "thumb": None,
             "bullets": [
                 "[[Deep Research Max]] が API 経由で利用可能に。MCP 対応・社内データ統合・グラフ生成を実装。",
                 "__非同期バックグラウンド調査__ で長時間タスクの自動化が現実解に。",
                 "Anthropic Managed Agents、OpenAI Operator と並び、3 強の長時間エージェント競争へ。",
             ]},
            {"score": 76, "time": "11:30", "source": "Intellectia",
             "title": "NVIDIA、時価総額 5 兆ドル突破──AI チップ需要継続で 4.3% 上昇",
             "url": "https://example.com/ai/5", "thumb": None,
             "bullets": [
                 "4/24 に [[NVIDIA 時価総額 $5 兆]] 突破。Intel 好決算が触媒となり半導体セクター全面高。",
                 "__AI インフラ需要__ は 2026 年も継続、設備投資ガイダンスは前年比 +35%。",
                 "競合の AMD MI450 採用が Meta で決定、独占体制には変化の兆しが見える。",
             ]},
        ],
    },
    {
        "id": "it",
        "name": "IT-Consulting",
        "nameEn": "IT & Consulting",
        "accent": "#2E6B52",
        "glyph": "▲",
        "summary": "コンサル業界で AI が本業化。BCG は売上の 25% が AI 関連、Accenture も大型投資を相次ぎ発表。",
        "items": [
            {"score": 90, "time": "07:30", "source": "Accenture Newsroom",
             "title": "Accenture × Google Cloud、Gemini Enterprise Acceleration Program 始動",
             "url": "https://example.com/it/1", "thumb": None,
             "bullets": [
                 "[[Accenture]] と Google Cloud が Gemini Enterprise Acceleration Program 始動。",
                 "__数千人体制__ でエンタープライズ AI 展開を支援、初年度の対象企業は 100 社規模。",
                 "Anthropic のマルチクラウド化と並び、ハイパースケーラー × グローバル SI の連携モデルが定着へ。",
             ]},
            {"score": 85, "time": "08:45", "source": "Metaintro",
             "title": "BCG、2025 年収益の 25%（$36 億）が AI 関連業務",
             "url": "https://example.com/it/2", "thumb": None,
             "bullets": [
                 "[[BCG]] 2025 年収益 $144 億のうち $36 億が AI 案件。前年比 __+58%__ の急拡大。",
                 "コンサル業界で AI が「本業」化した転換点を示す数字。Bain・McKinsey も追随傾向。",
                 "ピラミッド型スタッフィングの終焉、エントリー採用基準の AI スキル偏重が同時進行。",
             ]},
            {"score": 78, "time": "10:30", "source": "Stanford AI Index",
             "title": "Stanford AI Index 2026：AI エージェント成功率 66%──本番到達は 11〜14% のみ",
             "url": "https://example.com/it/3", "thumb": None,
             "bullets": [
                 "OSWorld ベンチマークで [[66% 達成]] も、企業本番導入は __11-14% のみ__ という実態。",
                 "PoC から本番への「死の谷」を越えるガバナンス・運用が、コンサル業界の新主戦場に。",
                 "Agentforce 等の事例では平均 ROI 171%。本番化できれば投資回収は速い。",
             ]},
            {"score": 72, "time": "11:00", "source": "FP Trendy",
             "title": "NTT グループ、国内データセンター IT 電力容量を 2033 年度までに 3 倍超へ",
             "url": "https://example.com/it/4", "thumb": None,
             "bullets": [
                 "NTT/NTTデータ/NTTドコモビジネスが [[2033 年度までに DC 電力容量 3 倍超]] 拡張。",
                 "__電力・冷却__ が今後の競争優位の鍵。生成 AI 需要の物理基盤を国内で確保する狙い。",
                 "国内 DC 競合（さくら/IDCF）も追随予想、電力調達競争が激化する局面に入った。",
             ]},
            {"score": 65, "time": "13:20", "source": "Infoseek/ITmedia",
             "title": "富士通・NTTデータ・NEC・ソフトバンク等が「xIPF コンソーシアム」設立",
             "url": "https://example.com/it/5", "thumb": None,
             "bullets": [
                 "産学 8 団体が [[xIPF コンソーシアム]] 設立。AI スペース構想で国産 AI 基盤連合を形成。",
                 "NTT データは __生成 AI によるシステム開発全面代替__ を 2026 年度導入予定。",
                 "海外 AI 強者への対抗軸を国内連合で作る動き、政府も実証予算で支援姿勢。",
             ]},
        ],
    },
    {
        "id": "economy",
        "name": "経済",
        "nameEn": "Economy",
        "accent": "#8E2A19",
        "glyph": "■",
        "summary": "日経平均が史上初の 6 万円台。日銀据え置きと FRB の慎重姿勢で日米金利差は方向感未定。",
        "items": [
            {"score": 94, "time": "07:00", "source": "日本経済新聞",
             "title": "日経平均、4 月 27 日に史上初の 6 万円台突破──ファナック急伸",
             "url": "https://example.com/economy/1", "thumb": None,
             "bullets": [
                 "日経平均が 4/27 終値 [[60,537 円]] と史上初 6 万円台。ファナック急伸が牽引役。",
                 "5 万→ 6 万円が約 __半年で史上最速__。フィジカル AI 相場の口火という解説が主流。",
                 "TOPIX も 4,200 ポイント超、東証グロースは小幅高に留まり指数間の温度差が顕在化。",
             ]},
            {"score": 86, "time": "08:00", "source": "日本経済新聞",
             "title": "日銀、4 月会合で政策金利 0.75% 据え置き──6 月へ判断先送り",
             "url": "https://example.com/economy/2", "thumb": None,
             "bullets": [
                 "日銀 4 月会合で [[0.75% 据え置き]] 確定。中東情勢を理由に 6 月会合に先送り。",
                 "市場は __6 月・10 月に各 25bp 利上げ__ を予想継続。OIS は 1.25% へのパスを織り込み。",
                 "為替への影響は限定的、ドル円は据え置き発表前後で 30 銭の小動きに留まった。",
             ]},
            {"score": 78, "time": "09:30", "source": "JETRO",
             "title": "FRB、年内 1 回の追加利下げ見通し──市場との乖離でドル高継続",
             "url": "https://example.com/economy/3", "thumb": None,
             "bullets": [
                 "FRB ドットチャートは [[年内 1 回利下げ]]。市場は 2 回を織り込む乖離があり、ドル高基調継続。",
                 "日米金利差は __縮小方向だが遅い__。輸出企業の為替予約は 5 月以降のヘッジ層が課題。",
                 "ECB との比較ではドル一強構造が継続、新興国通貨に下方圧力。",
             ]},
            {"score": 70, "time": "11:00", "source": "Reuters",
             "title": "米 GDP 第 1 四半期速報値、前期比年率 +2.8%──市場予想上回る",
             "url": "https://example.com/economy/4", "thumb": None,
             "bullets": [
                 "米 1Q GDP 速報値は [[+2.8%]] と市場予想 +2.5% を上回り、ソフトランディング期待が再燃。",
                 "個人消費が __+3.2%__ と力強く、サービス業中心に底堅さが続く。",
                 "FRB の慎重姿勢を裏付ける数字、利下げ織り込みの巻き戻しが米長期金利上昇に繋がっている。",
             ]},
            {"score": 60, "time": "13:00", "source": "Yahoo!ニュース",
             "title": "国内 4 月 CPI、前年比 +2.3%──サービス価格主導で粘着性",
             "url": "https://example.com/economy/5", "thumb": None,
             "bullets": [
                 "国内 4 月 CPI（生鮮除くコア）は前年比 [[+2.3%]]、3 か月連続で日銀目標を上回る。",
                 "サービス価格は __+2.1%__ で粘着性、賃金上昇の物価への反映が定着しつつある。",
                 "日銀の利上げ判断にとってはハト派要因が後退、6 月会合の利上げ確度がやや上昇。",
             ]},
        ],
    },
    {
        "id": "game",
        "name": "ゲーム",
        "nameEn": "Gaming",
        "accent": "#5E3D8C",
        "glyph": "●",
        "summary": "ウマ娘 4 周年で記録更新、Cygames は次世代 IP も準備。Switch 後継機の話題が再燃。",
        "items": [
            {"score": 88, "time": "08:00", "source": "ファミ通",
             "title": "ウマ娘 4 周年記念キャンペーン、ピーク同時接続が過去最高更新",
             "url": "https://example.com/game/1", "thumb": None,
             "bullets": [
                 "[[ウマ娘 4 周年]] のピーク同時接続が __前年比 +18%__、過去最高を更新。",
                 "新ウマ娘「ヴィヴラスファル」実装と限定衣装が課金牽引、初日売上推定 4 億円超。",
                 "Cygames は次世代スマホゲーの開発も並行、ロードマップは下半期に発表予定。",
             ]},
            {"score": 80, "time": "09:30", "source": "Bloomberg",
             "title": "任天堂、Switch 後継機の発売を 2026 年 11 月に正式アナウンス",
             "url": "https://example.com/game/2", "thumb": None,
             "bullets": [
                 "任天堂は [[Switch 2]]（仮称）を 2026 年 11 月発売と正式アナウンス。価格は $399 を中心軸。",
                 "__後方互換性__ を Switch 1 タイトル全てで維持、サブスク移行モデルも検討中との報道。",
                 "TSE 株価は時間外で +4.2%、E3 不在の年でゲーム業界最大のサプライズに。",
             ]},
            {"score": 73, "time": "11:00", "source": "GamesIndustry.biz",
             "title": "テンセント、Riot Games との統合戦略を強化──「Valorant」モバイル版始動",
             "url": "https://example.com/game/3", "thumb": None,
             "bullets": [
                 "[[テンセント]] と Riot Games が統合戦略を強化、Valorant Mobile を 6 月に開始。",
                 "中国本土向けは TiMi Studio が運営、__APAC esports__ 市場で Mobile Legends と直接競合。",
                 "ネットイース「永劫無間」とのモバイル領域競争も激化、PC eSports からの収益移転加速。",
             ]},
            {"score": 65, "time": "13:00", "source": "4Gamer",
             "title": "miHoYo、原神アップデート 5.5 を配信──新キャラ実装で売上ブースト",
             "url": "https://example.com/game/4", "thumb": None,
             "bullets": [
                 "[[miHoYo]] 原神 5.5 配信、新キャラ「フリーナ」実装で初週売上 __$8,200 万__ を記録。",
                 "崩壊スターレイル/ゼンレスゾーンゼロとあわせ、miHoYo グループ売上は四半期 $5 億超ペース。",
                 "上場準備の噂が再燃、香港 IPO 観測筋は 2027 年初頭を有力視。",
             ]},
            {"score": 55, "time": "14:30", "source": "Gematsu",
             "title": "SQUARE ENIX、FF14 拡張ディスク第 8 弾の体験版を公開",
             "url": "https://example.com/game/5", "thumb": None,
             "bullets": [
                 "[[SQUARE ENIX]] FF14 第 8 拡張「Eternity Echoes」体験版が無料公開。",
                 "MMO 業界の縮小トレンドに反し、__既存タイトルの長寿化__ で安定収益を確保する戦略。",
                 "国内ゲーム業界の出口戦略として、長寿 IP の海外展開強化が共通テーマに。",
             ]},
        ],
    },
]

REFLECTION = {
    "title": "金利の天井とAIの底入れ",
    "subtitle": "April 28 — 5 lenses converge on a single inflection",
    "lead": "本日 5 分野・40 本のニュースから浮かび上がる最大のテーマは、[[金利の天井]] と [[AI の底入れ]] の同時進行である。以下、各カテゴリを横断して読み解く。",
    "pull_quote": "「単一の強い製品」から「__エコシステムでの占有率__」へ──プラットフォーム経済が成熟期に入った日。",
    "sections": [
        {"tag": "総論", "accent": "#1A1A1A",
         "heading": "二大潮流の同期 — 金利天井と AI 底入れ",
         "body": "本日のニュース群を貫く構造は、[[金利環境の転換]] と [[AI 投資の本番化]] が同時に進行しているという事実である。これは単なる偶然ではなく、__金利低下が AI インフラ投資の資本コストを引き下げ__、AI 商流の拡大が逆に企業のキャッシュ需要を支えるという、相互強化のループを示している。"},
        {"tag": "為替・経済", "accent": "#B8860B",
         "heading": "日米金利差の縮小、ただし速度は緩慢",
         "body": "FOMC 議事要旨の利下げ示唆と日銀の据え置き継続で、日米金利差の方向感は [[縮小方向]] が確定。一方、市場の利下げ織り込み（年 2 回）と FRB ドット（年 1 回）の乖離は依然大きく、__ドル高基調が当面継続__ する公算。輸出企業の為替予約は 5 月以降の見直しが急務に。"},
        {"tag": "AI・技術", "accent": "#2D5BB8",
         "heading": "Anthropic vs OpenAI の連続版上げ競争",
         "body": "Claude Opus 4.7 と GPT-5.5 が同月内にリリースされ、__6 週間サイクル__ の連続版上げが恒常化。Microsoft の OpenAI 収益シェア廃止により、AI 商流は [[マルチクラウド化]] へ確定的にシフト。Google Deep Research Max の MCP 対応と合わせ、長時間エージェント領域での 3 強競争が形成された。"},
        {"tag": "産業・業界", "accent": "#2E6B52",
         "heading": "コンサル業界で AI が本業化、PoC 死の谷を越えるガバナンスが主戦場",
         "body": "BCG の AI 売上比率 [[25%]]、Accenture × Google Cloud の Gemini Acceleration、xIPF コンソーシアム──いずれも __AI を本業として組み込む__ ステージに突入したことを示す。一方、Stanford AI Index 2026 は本番到達率 11-14% という現実も突きつけており、PoC を本番化するガバナンス・運用能力がコンサルの新主戦場となる。"},
        {"tag": "明日へ", "accent": "#C9B98A",
         "heading": "今後 1 週間で見るべきイベント",
         "body": "明日以降のキーは、[[GDP 詳細データ]]（米 1Q 確報値、5/2）、[[FOMC 5 月会合]]（金利据え置き予想、政策声明文の文言注視）、[[Anthropic 開発者会議]]（Claude 5 系のロードマップ示唆の可能性）の 3 つ。__市場の織り込みズレが解消する週__ になるか、慎重に観察したい。"},
    ],
    "takeaways": [
        {"tag": "為替", "color": "#B8860B",
         "text": "日米金利差の縮小は[[構造的]]。投機ではなく実需のポジション調整局面に入った。"},
        {"tag": "AI", "color": "#2D5BB8",
         "text": "PoCから本番への[[フェーズ転換]]。エージェント実需化と規制具体化が両輪で進む。"},
        {"tag": "産業", "color": "#2E6B52",
         "text": "案件性質による[[二極化]]──従来型SI+1.2% vs 生成AI特化型+15%、中位層に最大の転換圧力。"},
    ],
    "related": [
        {"date": "2026-04-25", "title": "AI 基盤投資の踊り場──Hyperscaler の設備投資ガイダンス読み比べ",
         "url": "https://github.com/HIDEPON-UMG/News-Grasp/blob/main/digest/2026-04-25.md"},
        {"date": "2026-04-22", "title": "日銀タカ派化シナリオ再検証──賃金 vs サービス価格の鶏卵問題",
         "url": "https://github.com/HIDEPON-UMG/News-Grasp/blob/main/digest/2026-04-22.md"},
        {"date": "2026-04-15", "title": "コンサル AI 案件の不都合な真実──ROI 中央値と最頻値の乖離",
         "url": "https://github.com/HIDEPON-UMG/News-Grasp/blob/main/digest/2026-04-15.md"},
    ],
}
