# -*- coding: utf-8 -*-
"""2026-05-23 digest の articles.jsonl 追記スクリプト"""
import json, os

SEEN_AT = "2026-05-23T06:00:00+09:00"
DATE = "2026-05-23"
BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PATH = os.path.join(BASE, "data", "articles.jsonl")

new_entries = [
    # FX 1
    {"date": DATE, "seen_at": SEEN_AT, "genre": "FX",
     "title": "ドル円159円台で週終わり・日銀コアCPI 4年ぶり低水準 — 利上げ・介入の均衡点",
     "url": "https://www.fxempire.com/forecasts/article/japanese-yen-forecast-usd-jpy-rises-as-tokyo-inflation-hits-boj-target-1569746",
     "url_norm": "fxempire.com/forecasts/article/japanese-yen-forecast-usd-jpy-rises-as-tokyo-inflation-hits-boj-target-1569746",
     "source": "FXEmpire",
     "summary": "ドル円は5/22 NYクローズで159.18円と2週連続上昇。東京コアCPI1.4%（4年ぶり低水準）で9月利上げ観測に若干の陰りも、植田発言でスワップは利上げプライシングを継続。介入ライン160円が焦点。",
     "entities": {"companies": [], "countries": ["日本", "米国"], "services": [], "people": [], "tickers": ["USDJPY"]},
     "topics": ["利上げ観測", "CPI"], "industries": ["金融"], "events": ["政策会合"],
     "tags": ["cat/fx", "country/日本", "country/米国", "ticker/USDJPY", "topic/利上げ観測", "topic/CPI", "score/高"],
     "thumb": "https://responsive.fxempire.com/v7/_fxempire_/2025/09/USDJPY-1.jpg?func=cover&q=70&width=700"},
    # FX 2
    {"date": DATE, "seen_at": SEEN_AT, "genre": "FX",
     "title": "ヘッジファンドの円ショートが過去最大水準 — 160円介入ラインが週明けの焦点",
     "url": "https://www.bitmex.com/blog/usd-jpy-forecast-2026",
     "url_norm": "bitmex.com/blog/usd-jpy-forecast-2026",
     "source": "BitMEX Research",
     "summary": "CFTC・COTレポートでヘッジファンド円ショートが過去最大水準。BOJ利上げや介入で踏み上げリスク高。USD/JPYは159〜160円の均衡ゾーンで週明けを迎える。",
     "entities": {"companies": [], "countries": ["日本", "米国"], "services": [], "people": [], "tickers": ["USDJPY"]},
     "topics": ["為替介入", "ヘッジファンド"], "industries": ["金融"], "events": [],
     "tags": ["cat/fx", "country/日本", "country/米国", "ticker/USDJPY", "topic/為替介入", "score/高"],
     "thumb": "https://images.ctfassets.net/4d5b2rvh73n7/4H2u9dRFVsxnAwZZ2nh800/afd8d0c64b6d5a3c079e42e466b558f5/usdjpy-forecast-overview-2026.png"},
    # FX 3
    {"date": DATE, "seen_at": SEEN_AT, "genre": "FX",
     "title": "EUR/JPY 183円台・EUR/USD 1.17台 — ECBの次の一手が見えないまま方向感喪失",
     "url": "https://zai.diamond.jp/list/fxnews/index",
     "url_norm": "zai.diamond.jp/list/fxnews/index",
     "source": "ザイFX！",
     "summary": "EUR/JPYは183円台で高止まり。ECBの6月利上げ確率86%を織り込む一方、インフレ鈍化シグナルも出ており方向感なし。GBP/USDは1.34台で小動き。",
     "entities": {"companies": [], "countries": ["EU", "英国"], "services": [], "people": [], "tickers": ["EURJPY", "EURUSD", "GBPUSD"]},
     "topics": ["ECB", "金利"], "industries": [], "events": ["政策会合"],
     "tags": ["cat/fx", "country/EU", "country/英国", "ticker/EURJPY", "topic/ECB", "score/高"],
     "thumb": "https://zai.diamond.jp/mwimgs/9/e/-/img_9e47ac79ce2cf237f05d70fc22e16d45110540.png"},
    # FX 4
    {"date": DATE, "seen_at": SEEN_AT, "genre": "FX",
     "title": "USD/JPY 月次展望 — 「均衡なき均衡」156〜162円レンジの持続シナリオ",
     "url": "https://www.dailyforex.com/forex-technical-analysis/2026/04/usdjpy-forex-forecast-30-april-2026/244623",
     "url_norm": "dailyforex.com/forex-technical-analysis/2026/04/usdjpy-forex-forecast-30-april-2026/244623",
     "source": "DailyForex",
     "summary": "USD/JPYの月次予想は156〜162円レンジ膠着がベースシナリオ。Warsh議長タカ派で日銀との政策差はドル高圧力維持。AUD/USDはRBA利下げ後退で底堅い。",
     "entities": {"companies": [], "countries": ["米国", "日本", "豪州"], "services": [], "people": [], "tickers": ["USDJPY", "AUDUSD"]},
     "topics": ["金利差", "為替予測"], "industries": [], "events": [],
     "tags": ["cat/fx", "country/米国", "country/日本", "ticker/USDJPY", "topic/金利差", "score/中"],
     "thumb": "https://assets.dailyforex.com/images/articles/chatgpt-image-apr-30,-2026,-11_28_16-am.png"},
    # FX 5
    {"date": DATE, "seen_at": SEEN_AT, "genre": "FX",
     "title": "週次為替市場概観 — WarshタカHA派×BOJ打診の攻防で全主要通貨がレンジ内",
     "url": "https://www.forexfactory.com/market/usdjpy",
     "url_norm": "forexfactory.com/market/usdjpy",
     "source": "Forex Factory",
     "summary": "今週FX市場はWarsh FRBタカ派継続とBOJ利上げ打診の組み合わせが上値・下値を制限する異例の均衡。来週米雇用統計（6/6）が最大の方向性決定因子。",
     "entities": {"companies": [], "countries": ["米国"], "services": [], "people": [], "tickers": ["USDJPY"]},
     "topics": ["金融政策", "FOMC"], "industries": [], "events": [],
     "tags": ["cat/fx", "country/米国", "topic/FOMC", "score/中"],
     "thumb": "https://resources.faireconomy.media/images/logos/bookmark_ff_400.png"},
    # AI 1
    {"date": DATE, "seen_at": SEEN_AT, "genre": "AI",
     "title": "SpaceX・OpenAI・Anthropic、$4兆AI IPOウェーブ — AIバブルの到達点か転換点か",
     "url": "https://invezz.com/news/2026/05/23/fears-and-frenzy-mount-as-spacex-openai-and-anthropic-prepare-for-a-4t-ai-ipo-wave/",
     "url_norm": "invezz.com/news/2026/05/23/fears-and-frenzy-mount-as-spacex-openai-and-anthropic-prepare-for-a-4t-ai-ipo-wave",
     "source": "Invezz",
     "summary": "SpaceX S-1提出（$1.75兆）、OpenAI S-1提出（$8,520億）、Anthropic10月目標。3社合計$4兆という史上最大IPOウェーブが同時進行。Magnificent-7支配に競争が生まれる。",
     "entities": {"companies": ["OpenAI", "Anthropic", "SpaceX"], "countries": ["米国"], "services": [], "people": [], "tickers": []},
     "topics": ["IPO", "AI投資"], "industries": ["AI"], "events": ["IPO申請"],
     "tags": ["cat/ai", "co/OpenAI", "co/Anthropic", "co/SpaceX", "country/米国", "topic/IPO", "event/IPO申請", "score/高"],
     "thumb": "https://invezz-wp-media.lon1.digitaloceanspaces.com/2026/05/image-1779465251.png"},
    # AI 2
    {"date": DATE, "seen_at": SEEN_AT, "genre": "AI",
     "title": "OpenAI内部モデルが80年来の幾何学予想を独力で証明 — Fields賞受賞者「AI数学の画期的一歩」",
     "url": "https://www.buildfastwithai.com/blogs/ai-news-today-may-23-2026",
     "url_norm": "buildfastwithai.com/blogs/ai-news-today-may-23-2026",
     "source": "BuildFastWithAI",
     "summary": "OpenAIの非公開内部モデルが80年間解けなかった幾何学予想を自律的に証明。Fields賞受賞者ティム・ガワーズ氏が画期的マイルストーンと評価。AGIへの議論を再燃。",
     "entities": {"companies": ["OpenAI", "Anthropic"], "countries": ["米国", "英国"], "services": [], "people": ["ジャック・クラーク"], "tickers": []},
     "topics": ["AI研究", "数学"], "industries": ["AI"], "events": [],
     "tags": ["cat/ai", "co/OpenAI", "co/Anthropic", "country/米国", "topic/AI研究", "score/高"],
     "thumb": "https://oukdqujzonxvqhiefdsv.supabase.co/storage/v1/object/public/blogs/9b52226d-1748-4109-af0d-f0324c416445.png"},
    # AI 3
    {"date": DATE, "seen_at": SEEN_AT, "genre": "AI",
     "title": "Trump政権がAIセーフティ大統領令を廃止 — マスク・ザッカー・サックスの直接ロビーで即日撤回",
     "url": "https://singhajit.com/dev-weekly/2026/may-18-24/google-io-2026-anthropic-stainless-spacex-ipo-openai-ipo-meta-layoffs-laravel-lang-attack/",
     "url_norm": "singhajit.com/dev-weekly/2026/may-18-24/google-io-2026-anthropic-stainless-spacex-ipo-openai-ipo-meta-layoffs-laravel-lang-attack",
     "source": "Ajit Singh Dev Weekly",
     "summary": "Trump政権がAI安全大統領令を廃止。マスク・ザッカーバーグ・サックスが直接電話で撤廃実現。Meta 8,000人解雇当日に社員データ流用音声もリーク。",
     "entities": {"companies": ["Meta", "OpenAI"], "countries": ["米国"], "services": [], "people": ["イーロン・マスク", "マーク・ザッカーバーグ"], "tickers": []},
     "topics": ["AI規制", "レイオフ"], "industries": ["AI"], "events": ["規制公表"],
     "tags": ["cat/ai", "co/Meta", "country/米国", "topic/AI規制", "event/規制公表", "score/高"],
     "thumb": "https://singhajit.com/assets/img/posts/dev_weekly/tech-news-18-24may-2026.png"},
    # AI 4
    {"date": DATE, "seen_at": SEEN_AT, "genre": "AI",
     "title": "Anthropic初の黒字化・年収$10.9B達成 & Stainless買収でAPI開発者体験を強化",
     "url": "https://medium.com/no-time/openai-spacex-and-anthropic-just-entered-the-ipo-wars-f7ecf4403e72",
     "url_norm": "medium.com/no-time/openai-spacex-and-anthropic-just-entered-the-ipo-wars-f7ecf4403e72",
     "source": "Medium (No Time)",
     "summary": "Anthropicが初の黒字化・年収$10.9Bを公表。Stainless（API向けSDKビルダー）を5/18買収。Karpathyが5/19に入社しプレトレーニング研究チームを率いる。",
     "entities": {"companies": ["Anthropic", "OpenAI"], "countries": ["米国"], "services": ["Claude", "Stainless"], "people": ["アンドレイ・カルパシー"], "tickers": []},
     "topics": ["AI投資", "M&A"], "industries": ["AI"], "events": ["決算", "M&A"],
     "tags": ["cat/ai", "co/Anthropic", "country/米国", "topic/AI投資", "event/決算", "score/高"],
     "thumb": "https://miro.medium.com/v2/resize:fit:1200/1*i0svggt4Hn6b0YeaICnWQA.png"},
    # AI 5
    {"date": DATE, "seen_at": SEEN_AT, "genre": "AI",
     "title": "GitHub 3,800リポジトリ流出 — AI開発インフラのサイバーリスクが顕在化",
     "url": "https://techjournal.org/spacex-openai-anthropic-ipo-2026",
     "url_norm": "techjournal.org/spacex-openai-anthropic-ipo-2026",
     "source": "TechJournal",
     "summary": "GitHubが5/20に約3,800内部リポジトリの流出を確認。脅威アクターTeamPCP（Google TIG: UNC6780）によるもの。AI開発インフラへのサイバーリスクが顕在化。",
     "entities": {"companies": ["OpenAI", "Google"], "countries": ["米国"], "services": ["GitHub"], "people": [], "tickers": []},
     "topics": ["サイバーセキュリティ", "AI"], "industries": ["AI"], "events": [],
     "tags": ["cat/ai", "co/OpenAI", "co/Google", "country/米国", "topic/サイバーセキュリティ", "score/中"],
     "thumb": "https://techjournal.org/wp-content/uploads/2026/05/openai-ipo-2026.jpg"},
    # IT 1
    {"date": DATE, "seen_at": SEEN_AT, "genre": "IT-Consulting",
     "title": "Deloitte、Google Cloud Agentic Transformation Practiceを正式設立 — Gemini Enterprise 10万名展開",
     "url": "https://www.deloitte.com/us/en/about/press-room/deloitte-launches-google-cloud-agentic-transformation-practice.html",
     "url_norm": "deloitte.com/us/en/about/press-room/deloitte-launches-google-cloud-agentic-transformation-practice.html",
     "source": "Deloitte Press Release",
     "summary": "DeloitteがGoogle Cloud専任Agentic Transformation Practiceを設立。10万名以上にGemini Enterprise展開。FDE共同派遣を受け、コンサル二極化を主導。",
     "entities": {"companies": ["デロイト", "Google"], "countries": ["米国"], "services": ["Gemini"], "people": [], "tickers": []},
     "topics": ["AIエージェント", "生成AI導入"], "industries": ["IT-コンサル"], "events": ["組織発表"],
     "tags": ["cat/it", "co/デロイト", "co/Google", "country/米国", "topic/AIエージェント", "event/組織発表", "score/高"],
     "thumb": "https://media.deloitte.com/is/image/deloitte/AI_1_AdobeStock_285825086:1200-x-627"},
    # IT 2
    {"date": DATE, "seen_at": SEEN_AT, "genre": "IT-Consulting",
     "title": "Google Cloud × パートナーエコシステム — NTTデータ5,000名体制の全容",
     "url": "https://cloud.google.com/blog/topics/partners/how-google-cloud-partner-ecosystem-is-building-the-agentic-enterprise",
     "url_norm": "cloud.google.com/blog/topics/partners/how-google-cloud-partner-ecosystem-is-building-the-agentic-enterprise",
     "source": "Google Cloud Blog",
     "summary": "NTTデータが5,000名のGoogle Cloud専任体制を整備。パートナー収益はGoogle Cloud 1ドルに対し$7.05。KPMG $100M・PwC $400Mコミット、Accenture 450件以上稼働。",
     "entities": {"companies": ["Google", "NTTデータ", "KPMG", "PwC", "アクセンチュア"], "countries": ["米国", "日本"], "services": ["Gemini"], "people": [], "tickers": []},
     "topics": ["AIエージェント", "IT投資"], "industries": ["IT-コンサル"], "events": [],
     "tags": ["cat/it", "co/Google", "co/NTTデータ", "co/アクセンチュア", "country/米国", "country/日本", "topic/AIエージェント", "score/高"],
     "thumb": "https://storage.googleapis.com/gweb-cloudblog-publish/images/GCN26_102_BlogHeader_2436x1200_Opt_20_Dark.max-2500x2500.jpg"},
    # IT 3
    {"date": DATE, "seen_at": SEEN_AT, "genre": "IT-Consulting",
     "title": "Google Cloud $750Mパートナーファンドの経済波及 — コンサル側から見た「7倍収益」の仕組み",
     "url": "https://aimagazine.com/news/google-cloud-agentic-ai-adoption-fund",
     "url_norm": "aimagazine.com/news/google-cloud-agentic-ai-adoption-fund",
     "source": "AI Magazine",
     "summary": "Google Cloud $750Mパートナーファンドの波及分析。AI実装大手はコスト20%削減を実証、中小SIerはパイロット止まりで格差拡大。",
     "entities": {"companies": ["Google", "アクセンチュア", "デロイト"], "countries": ["米国"], "services": [], "people": [], "tickers": []},
     "topics": ["DX", "AI投資"], "industries": ["IT-コンサル"], "events": [],
     "tags": ["cat/it", "co/Google", "co/アクセンチュア", "country/米国", "topic/DX", "score/高"],
     "thumb": "https://assets.bizclikmedia.net/1200/b205c09e743febe16f6e5869f6ddf92f:9c68ff44ac72b34424bf409d6c322bf0/gettyimages-1181670972.jpg.jpg"},
    # IT 4
    {"date": DATE, "seen_at": SEEN_AT, "genre": "IT-Consulting",
     "title": "Accenture × Google Cloud — Gemini Enterprise搭載の「アジェンティック変革」をグローバル展開",
     "url": "https://newsroom.accenture.com/news/2026/accenture-and-google-cloud-expand-partnership-to-scale-agentic-transformation-for-global-enterprises-with-gemini-enterprise",
     "url_norm": "newsroom.accenture.com/news/2026/accenture-and-google-cloud-expand-partnership-to-scale-agentic-transformation-for-global-enterprises-with-gemini-enterprise",
     "source": "Accenture Newsroom",
     "summary": "AccentureがGoogle CloudとのパートナーシップでGemini Enterpriseをグローバル展開。450件以上のAIエージェントを本番稼働。MBBのAI収益の約10倍の売上$65B。",
     "entities": {"companies": ["アクセンチュア", "Google"], "countries": ["米国"], "services": ["Gemini"], "people": [], "tickers": []},
     "topics": ["AIエージェント", "生成AI導入"], "industries": ["IT-コンサル"], "events": [],
     "tags": ["cat/it", "co/アクセンチュア", "co/Google", "country/米国", "topic/AIエージェント", "score/中"],
     "thumb": "https://newsroom.accenture.com/news/2026/media_127d2a3b2f4fddbd6f6d94d01345cb0f3b6f24654.png?width=1200&format=pjpg&optimize=medium"},
    # IT 5
    {"date": DATE, "seen_at": SEEN_AT, "genre": "IT-Consulting",
     "title": "Google CloudがパートナーをAgentic AI実装の最前線へ — Azureとの差別化戦略",
     "url": "https://www.channele2e.com/news/google-cloud-pushes-partners-deeper-into-agentic-ai-delivery",
     "url_norm": "channele2e.com/news/google-cloud-pushes-partners-deeper-into-agentic-ai-delivery",
     "source": "ChannelE2E",
     "summary": "Google CloudがFDE派遣プログラムを拡充し7社をFDE共同配置の第一優先と位置づけ。Gemini Agent Builderを無償提供でパートナーに先行解放。エコシステム乗数$7.05で競合と差別化。",
     "entities": {"companies": ["Google", "アクセンチュア", "デロイト"], "countries": ["米国"], "services": ["Gemini"], "people": [], "tickers": []},
     "topics": ["DX", "クラウド"], "industries": ["IT-コンサル"], "events": [],
     "tags": ["cat/it", "co/Google", "co/アクセンチュア", "country/米国", "topic/クラウド", "score/中"],
     "thumb": "https://files.cyberriskalliance.com/wp-content/uploads/2026/02/AdobeStock_1794438123-scaled.jpeg"},
    # Game 1
    {"date": DATE, "seen_at": SEEN_AT, "genre": "Game",
     "title": "新作「Star Fox」Switch 2向けに6月25日発売確定 — N64版を刷新、8人オンライン対戦搭載",
     "url": "https://www.famitsu.com/article/202605/74033",
     "url_norm": "famitsu.com/article/202605/74033",
     "source": "ファミ通",
     "summary": "任天堂がStar Fox新作の6/25発売を再確認。N64版ベースにグラフィックを刷新、ジェームズ・マクラウドのエピソード追加、8人オンライン対戦搭載。DL版5,480円。",
     "entities": {"companies": ["任天堂"], "countries": ["日本"], "services": ["Switch-2"], "people": ["宮本茂"], "tickers": ["7974"]},
     "topics": ["新作発売", "任天堂"], "industries": ["ゲーム"], "events": ["製品発表"],
     "tags": ["cat/game", "co/任天堂", "country/日本", "topic/任天堂", "event/製品発表", "score/高"],
     "thumb": "https://cimg.kgl-systems.io/camion/files/74033/thumbnail_SaBd.jpg?x=1280"},
    # Game 2
    {"date": DATE, "seen_at": SEEN_AT, "genre": "Game",
     "title": "宮本茂「次のMarioゲームがとても楽しみ」— Switch 2の次の大波を示唆",
     "url": "https://mynintendonews.com/2026/05/23/shigeru-miyamoto-said-hes-really-looking-forward-to-the-next-mario-game/",
     "url_norm": "mynintendonews.com/2026/05/23/shigeru-miyamoto-said-hes-really-looking-forward-to-the-next-mario-game",
     "source": "My Nintendo News",
     "summary": "宮本茂がSwitch 2向け次のMarioゲームへの期待を示唆。Switch 2ラインナップの次の大波となるか、秋以降の布石として注目される。",
     "entities": {"companies": ["任天堂"], "countries": ["日本"], "services": ["Switch-2"], "people": ["宮本茂"], "tickers": ["7974"]},
     "topics": ["任天堂", "新作ゲーム"], "industries": ["ゲーム"], "events": [],
     "tags": ["cat/game", "co/任天堂", "country/日本", "person/宮本茂", "topic/任天堂", "score/高"],
     "thumb": "https://i0.wp.com/mynintendonews.com/wp-content/uploads/2025/08/mario.jpg?fit=1600%2C900&ssl=1"},
    # Game 3
    {"date": DATE, "seen_at": SEEN_AT, "genre": "Game",
     "title": "Nintendo Switch eShopチャート 5/23 — Tomodachi Lifeが断然首位、Bubsy 4Dが新規ランクイン",
     "url": "https://nintendoeverything.com/nintendo-switch-eshop-charts-may-23-2026/",
     "url_norm": "nintendoeverything.com/nintendo-switch-eshop-charts-may-23-2026",
     "source": "Nintendo Everything",
     "summary": "5/23週eShopランキングでTomodachi Life: Living the Dreamが首位継続。5/22発売Bubsy 4Dが上位入り。Switch 2ダウンロード比率がSwitch 1同時期比45%高い。",
     "entities": {"companies": ["任天堂"], "countries": ["日本", "米国"], "services": ["Switch-2"], "people": [], "tickers": ["7974"]},
     "topics": ["ソーシャルゲーム", "ゲーム市場"], "industries": ["ゲーム"], "events": [],
     "tags": ["cat/game", "co/任天堂", "country/日本", "topic/ゲーム市場", "score/高"],
     "thumb": "https://nintendoeverything.com/wp-content/uploads/Tomodachi-1.jpg"},
    # Game 4
    {"date": DATE, "seen_at": SEEN_AT, "genre": "Game",
     "title": "Nintendo Switch 2 — 6月は3大タイトル集中（FF7 Rebirth・Star Fox・Splatoon Raiders確認）",
     "url": "https://gamerant.com/nintendo-switch-2-new-games-coming-out-soon-list-june-2026/",
     "url_norm": "gamerant.com/nintendo-switch-2-new-games-coming-out-soon-list-june-2026",
     "source": "Game Rant",
     "summary": "6月Switch 2主要リリース: FF VII Rebirth (6/3)・Star Fox (6/25)の2本と7/23のSplatoon Raiders。スクウェア・エニックスのマルチ戦略がSwitch 2充実に直結。",
     "entities": {"companies": ["任天堂", "スクウェア・エニックス", "SIE"], "countries": ["日本"], "services": ["Switch-2"], "people": [], "tickers": ["7974", "9684"]},
     "topics": ["新作発売", "ゲーム市場"], "industries": ["ゲーム"], "events": ["製品発表"],
     "tags": ["cat/game", "co/任天堂", "co/スクウェア・エニックス", "country/日本", "topic/新作発売", "event/製品発表", "score/中"],
     "thumb": "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2026/05/switch-2-games-june-2026.jpg?w=1600&h=900&fit=crop"},
    # Game 5 (続報)
    {"date": DATE, "seen_at": SEEN_AT, "genre": "Game",
     "title": "Cygames Q2 英語版ウマ娘が海外好調続伸 — KY Derby後も北米・欧州流入が継続",
     "url": "https://gamebiz.jp/news/425182",
     "url_norm": "gamebiz.jp/news/425182",
     "source": "GameBiz",
     "summary": "Cygames Q2の英語版ウマ娘が北米・欧州でヒット継続。KY Derby後（5/2）の現地流入が持続。GWキャンペーンと連動し国内も回復、国内外ダブル好調が継続。",
     "entities": {"companies": ["Cygames"], "countries": ["日本", "米国"], "services": ["ウマ娘"], "people": [], "tickers": []},
     "topics": ["ソーシャルゲーム", "ゲーム市場"], "industries": ["ゲーム"], "events": [],
     "tags": ["cat/game", "co/Cygames", "country/日本", "topic/ソーシャルゲーム", "score/中"],
     "thumb": "https://i3.gamebiz.jp/media/aac40ca6-3ac0-490f-9a13-836b059ae5ed.jpg"},
]

with open(PATH, 'a', encoding='utf-8') as f:
    for entry in new_entries:
        f.write(json.dumps(entry, ensure_ascii=False) + '\n')

print("Added {} entries to articles.jsonl".format(len(new_entries)))
with open(PATH, encoding='utf-8') as f:
    total = sum(1 for _ in f)
print("Total lines: {}".format(total))
