"""2026-05-29 digest articles を articles.jsonl に追記するスクリプト"""
import json, urllib.parse, re

def normalize_url(url):
    try:
        p = urllib.parse.urlparse(url.strip())
        qs = urllib.parse.parse_qs(p.query, keep_blank_values=True)
        remove = {k for k in qs if re.match(r'^(utm_|ref$|fbclid|gclid|sessionid|mc_eid)', k)}
        qs2 = {k: v for k, v in qs.items() if k not in remove}
        new_q = urllib.parse.urlencode(qs2, doseq=True)
        path = p.path.rstrip('/')
        host = re.sub(r'^m\.', '', (p.hostname or '').lower())
        return f"{host}{path}" + (f"?{new_q}" if new_q else "")
    except Exception:
        return url

ARTICLES = [
    # FX
    {"genre":"FX","score":92,"title":"ドル円159円台前半 — 米・イラン合意報道でドル安が優勢","url":"https://fx.minkabu.jp/news/368505","source":"みんかぶ","thumb":"https://mfx-assets.s3.ap-northeast-1.amazonaws.com/news_ogp/forex.png","summary":"米・イラン停戦延長合意報道でドル安が優勢となり、ドル円は159.21円台前半まで下落。","entities":{"companies":[],"countries":["米国","イラン"],"services":[],"people":[],"tickers":["USDJPY"]},"topics":["為替介入"],"industries":["金融"],"events":[],"tags":["country/米国","country/イラン","ticker/USDJPY","topic/為替介入","industry/金融","score/高"]},
    {"genre":"FX","score":90,"title":"外国為替平衡操作の実施状況 — 財務省5月月次公表","url":"https://www.mof.go.jp/policy/international_policy/reference/feio/data/monthly/index.html","source":"財務省","thumb":"https://www.mof.go.jp/common/images/og_img.png","summary":"財務省が4〜5月分の介入実績を公表。推計8.6〜10兆円規模の円買い介入が実施されたとされる。","entities":{"companies":[],"countries":["日本"],"services":[],"people":[],"tickers":["USDJPY"]},"topics":["為替介入"],"industries":["金融"],"events":["政策発表"],"tags":["country/日本","ticker/USDJPY","topic/為替介入","industry/金融","event/政策発表","score/高"]},
    {"genre":"FX","score":88,"title":"日銀の6月利上げは長期金利安定の最低条件 — 野村證券分析","url":"https://www.nomura.co.jp/wealthstyle/article/0739/","source":"野村證券","thumb":"https://www.nomura.co.jp/wealthstyle/article/0739/images/og_a_0739_01.png","summary":"野村証券が6月利上げは長期金利安定の最低条件と指摘。日銀の6月利上げ確率は75%程度を織り込んだ。","entities":{"companies":["野村證券"],"countries":["日本"],"services":[],"people":[],"tickers":["USDJPY"]},"topics":["利上げ"],"industries":["金融"],"events":[],"tags":["co/野村證券","country/日本","ticker/USDJPY","topic/利上げ","industry/金融","score/高"]},
    {"genre":"FX","score":88,"title":"本日の注目点：ドル円一時159円25銭 — 東京CPI・介入実績発表が焦点","url":"https://finance.yahoo.co.jp/news/detail/fe69ddfdf9b543b1d6eb8724766181feb4f52407","source":"Yahoo!ファイナンス","thumb":"https://s.yimg.jp/images/finance/common/image/ogp.png","summary":"東京都区部CPI5月速報値と財務省介入実績公表が日銀6月利上げ判断に直結。ドル円は一時159円25銭まで上昇。","entities":{"companies":[],"countries":["日本"],"services":[],"people":[],"tickers":["USDJPY"]},"topics":["CPI"],"industries":["金融"],"events":["経済指標"],"tags":["country/日本","ticker/USDJPY","topic/CPI","industry/金融","event/経済指標","score/高"]},
    {"genre":"FX","score":85,"title":"Japanese Yen Forecast: USD/JPY Jumps After Japan CPI Slide","url":"https://www.fxempire.com/forecasts/article/japanese-yen-forecast-usd-jpy-jumps-after-japan-cpi-slide-1580747","source":"FX Empire","thumb":"https://responsive.fxempire.com/v7/_fxempire_/2025/09/USDJPY-1.jpg?func=cover&q=70&width=700","summary":"東京CPI鈍化を受けてUSD/JPYが上昇。日銀の6月利上げ確率が低下するとの観測から円売りが広がった。","entities":{"companies":[],"countries":["日本","米国"],"services":[],"people":[],"tickers":["USDJPY"]},"topics":["利上げ"],"industries":["金融"],"events":[],"tags":["country/日本","country/米国","ticker/USDJPY","topic/利上げ","industry/金融","score/高"]},
    # AI
    {"genre":"AI","score":98,"title":"AnthropicがシリーズHで650億ドル調達 — 評価額9,650億ドルでOpenAIを抜き世界最高値に","url":"https://techcrunch.com/2026/05/28/anthropic-raises-65-billion-nears-1t-valuation-ahead-of-ipo/","source":"TechCrunch","thumb":"https://techcrunch.com/wp-content/uploads/2025/09/Screenshot-2025-09-02-at-12.22.37PM.png?resize=1200,671","summary":"AnthropicがシリーズHで650億ドルを調達し評価額9,650億ドルに。OpenAIを抜き世界最高値プライベートAI企業となった。","entities":{"companies":["Anthropic","OpenAI"],"countries":["米国"],"services":["Claude","Claude-Code"],"people":[],"tickers":[]},"topics":["資金調達","AI"],"industries":["AI"],"events":["資金調達"],"tags":["co/Anthropic","co/OpenAI","country/米国","svc/Claude","topic/AI","industry/AI","event/資金調達","score/高"]},
    {"genre":"AI","score":95,"title":"OpenAIがGoldman Sachs主幹でIPO向け機密S-1書類をSECに提出","url":"https://www.cnbc.com/2026/05/20/openai-ipo-filing.html","source":"CNBC","thumb":"https://image.cnbcfm.com/api/v1/image/108276787-1773253292188-gettyimages-2265445220-BLACKROCK_INFRASTRUCTURE_SUMMIT.jpeg?v=1779296174&w=1920&h=1080","summary":"OpenAIが5月22日にSECへ機密IPO目論見書を提出。2026年9月上場を目標に評価額8,520億〜1兆ドルを目指す。","entities":{"companies":["OpenAI","GoldmanSachs","MorganStanley"],"countries":["米国"],"services":["ChatGPT"],"people":[],"tickers":[]},"topics":["IPO","AI"],"industries":["AI"],"events":["IPO"],"tags":["co/OpenAI","co/GoldmanSachs","country/米国","svc/ChatGPT","topic/IPO","industry/AI","event/IPO","score/高"]},
    {"genre":"AI","score":90,"title":"NVIDIA Q1 FY2027決算 — 売上816億ドル+85%、データセンターが全収益の87%","url":"https://intellectia.ai/blog/nvda-stock-earnings-analysis-may-2026","source":"Intellectia AI","thumb":None,"summary":"NVIDIAが売上816億ドル(前年比+85%)で過去最高を記録。データセンター収益391億ドルが全収益の87%。","entities":{"companies":["NVIDIA"],"countries":["米国"],"services":[],"people":[],"tickers":["NVDA"]},"topics":["AI","半導体"],"industries":["AI","半導体"],"events":["決算"],"tags":["co/NVIDIA","country/米国","ticker/NVDA","topic/AI","industry/半導体","event/決算","score/高"]},
    {"genre":"AI","score":84,"title":"Metaが「Meta One」サブスク世界展開 — Instagram/Facebook/WhatsApp有料プラン開始","url":"https://techcrunch.com/2026/05/27/meta-officially-launches-instagram-facebook-and-whatsapp-subscriptions-with-more-to-come-including-ai-plans/","source":"TechCrunch","thumb":"https://techcrunch.com/wp-content/uploads/2026/05/meta-apps-GettyImages-2164040793.jpg?w=1024","summary":"Metaが月額3.99〜19.99ドルのMeta Oneサブスクプランを世界展開。AI機能を課金モデルに組み込む戦略が始動した。","entities":{"companies":["Meta"],"countries":["米国"],"services":["Meta-One","Instagram","WhatsApp"],"people":[],"tickers":["META"]},"topics":["サブスクリプション","AI"],"industries":["AI"],"events":["製品発表"],"tags":["co/Meta","country/米国","ticker/META","topic/AI","industry/AI","event/製品発表","score/中"]},
    {"genre":"AI","score":78,"title":"富士通が自己進化マルチAIエージェント技術を開発 — 業務実行中に平均28ポイント精度向上","url":"https://global.fujitsu/en-global/pr/news/2026/05/25-01","source":"Fujitsu Global","thumb":"https://global.fujitsu/-/media/Project/Fujitsu/Fujitsu-HQ/pr/news/common/ogp/news-ogp-ai02.png?rev=b2c92af86d8c4104ad3ab0c62589d393","summary":"富士通が複数AIエージェントが業務を遂行しながら自律学習する技術を発表。Takane適用で平均28pt精度向上を確認。","entities":{"companies":["富士通"],"countries":["日本"],"services":["Takane"],"people":[],"tickers":[]},"topics":["AIエージェント"],"industries":["AI"],"events":["製品発表"],"tags":["co/富士通","country/日本","svc/Takane","topic/AIエージェント","industry/AI","event/製品発表","score/中"]},
    # IT-Consulting
    {"genre":"IT-Consulting","score":92,"title":"AccentureとHUMAIN、サウジアラビアでAI導入を官民横断で加速","url":"https://newsroom.accenture.com/news/2026/humain-and-accenture-accelerate-ai-adoption-at-scale-across-public-and-private-sectors-in-saudi-arabia","source":"Accenture Newsroom","thumb":"https://newsroom.accenture.com/default-meta-image.png?width=1200&format=pjpg&optimize=medium","summary":"AccentureとサウジアラビアPIF傘下HUMAINが戦略的パートナーシップを締結。官民のAI実装を本番運用に移行させる。","entities":{"companies":["Accenture","HUMAIN"],"countries":["サウジアラビア","米国"],"services":[],"people":[],"tickers":["ACN"]},"topics":["AI導入","DX"],"industries":["IT-コンサル"],"events":["提携発表"],"tags":["co/Accenture","co/HUMAIN","country/サウジアラビア","ticker/ACN","topic/AI導入","industry/IT-コンサル","event/提携発表","score/高"]},
    {"genre":"IT-Consulting","score":91,"title":"富士通、AnthropicおよびOpenAIと提携し法人向けAI営業を強化","url":"https://www.nikkei.com/article/DGXZQOUC275S50X20C26A5000000/","source":"日本経済新聞","thumb":"https://article-image-ix.nikkei.com/https%3A%2F%2Fimgix-proxy.n8s.jp%2FDSXZQO3081848027052026000000-1.jpg?auto=compress&bg=FFFF&crop=focalpoint&fit=crop&fm=jpg&h=630&w=1200&s=da72e0b4557ecac8d35e44f22295fc17","summary":"富士通がAnthropicとOpenAIの両社と提携を発表。法人向けサービス開発にClaudeを活用するマルチモデル戦略を採用。","entities":{"companies":["富士通","Anthropic","OpenAI"],"countries":["日本"],"services":["Claude"],"people":[],"tickers":[]},"topics":["AI導入","DX"],"industries":["IT-コンサル"],"events":["提携発表"],"tags":["co/富士通","co/Anthropic","country/日本","svc/Claude","topic/AI導入","industry/IT-コンサル","event/提携発表","score/高"]},
    {"genre":"IT-Consulting","score":90,"title":"NEC・日立・富士通が相次ぎAnthropicと提携 — 国内IT大手3社のAI戦略が鮮明","url":"https://www.itmedia.co.jp/business/articles/2605/27/news119.html","source":"ITmedia ビジネスオンライン","thumb":"https://image.itmedia.co.jp/business/articles/2605/27/cover_news119.jpg","summary":"NECに続き日立・富士通がAnthropicとの協業を発表。国内IT大手3社がClaude採用でそろい踏みとなった。","entities":{"companies":["NEC","日立","富士通","Anthropic"],"countries":["日本"],"services":["Claude"],"people":[],"tickers":[]},"topics":["AI導入","DX"],"industries":["IT-コンサル"],"events":["提携発表"],"tags":["co/NEC","co/日立","co/富士通","country/日本","svc/Claude","topic/AI導入","industry/IT-コンサル","event/提携発表","score/高"]},
    {"genre":"IT-Consulting","score":89,"title":"McKinsey、AIエージェントをコンサルタントのチーム配置選定に活用する計画","url":"https://www.bloomberg.com/news/articles/2026-05-01/mckinsey-plans-to-use-ai-agents-to-help-choose-client-teams","source":"Bloomberg","thumb":None,"summary":"McKinseyが4万人規模のコンサルタント配置にAIエージェントを活用すると発表。社内AILilliが月50万プロンプト超を処理。","entities":{"companies":["McKinsey"],"countries":["米国"],"services":["Lilli"],"people":[],"tickers":[]},"topics":["AIエージェント","DX"],"industries":["IT-コンサル"],"events":[],"tags":["co/McKinsey","country/米国","topic/AIエージェント","industry/IT-コンサル","score/高"]},
    {"genre":"IT-Consulting","score":87,"title":"NTTデータグループ 2025年度決算 — AIフルスタック体制でFY2030 EBITDA1.2兆円へ","url":"https://www.nttdata.com/global/ja/news/release/2026/050806/","source":"NTTデータグループ","thumb":"https://www.nttdata.com/global/ja/-/media/assets/images/sns_share.png?rev=583d5951ace649c08be7a88679328a3b","summary":"NTTデータグループが2025年度通期決算を発表。AIを中核とした成長戦略でFY2030 EBITDA1.2兆円目標を提示。","entities":{"companies":["NTTデータ"],"countries":["日本"],"services":[],"people":[],"tickers":[]},"topics":["DX","AI"],"industries":["IT-コンサル"],"events":["決算"],"tags":["co/NTTデータ","country/日本","topic/DX","industry/IT-コンサル","event/決算","score/高"]},
    # Mobility
    {"genre":"Mobility","score":95,"title":"WaymoがOjai第6世代ロボタクシーを一部ライダーに公開開放 — サンディエゴ・ラスベガス展開へ","url":"https://www.cnbc.com/2026/05/28/waymo-opens-ojai-robotaxis-to-some-riders-aims-to-lower-cost-of-fleet.html","source":"CNBC","thumb":"https://image.cnbcfm.com/api/v1/image/108261073-1770161242648-gettyimages-2259268678-ALPHABET_EARNS.jpeg?v=1770161334&w=1920&h=1080","summary":"WaymoがZeekr製第6世代ロボタクシーOjaiをSF/LA/フェニックスの一部ユーザーに無料開放。コスト削減実現。","entities":{"companies":["Waymo","Zeekr","Alphabet"],"countries":["米国"],"services":["Ojai"],"people":[],"tickers":["GOOGL"]},"topics":["自動運転","Robotaxi"],"industries":["モビリティ","自動運転"],"events":["製品発表"],"tags":["co/Waymo","co/Zeekr","country/米国","ticker/GOOGL","topic/自動運転","industry/モビリティ","event/製品発表","score/高"]},
    {"genre":"Mobility","score":92,"title":"IEA「Global EV Outlook 2026」 — 世界EV販売2,300万台、新車の28%に","url":"https://www.iea.org/reports/global-ev-outlook-2026","source":"IEA","thumb":"https://iea.imgix.net/5ba2f5b7-885c-4f0c-b015-fecda65514a8/GlobalEVOutlook2026_GettyImages-1471913353.jpg?auto=compress%2Cformat&fit=min&h=600&q=80&rect=2111%2C322%2C2678%2C2678&w=1200","summary":"IEAが2026年EV販売2,300万台（新車の28%）予測を発表。中国55%・欧州28%のシェアを詳報。","entities":{"companies":[],"countries":["中国","米国","EU"],"services":[],"people":[],"tickers":[]},"topics":["EV化"],"industries":["モビリティ","EV"],"events":[],"tags":["country/中国","country/EU","topic/EV化","industry/EV","score/高"]},
    {"genre":"Mobility","score":90,"title":"テキサス州、操縦装置なし完全自動運転を合法化 — Tesla Cybercab量産加速に直結","url":"https://techxplore.com/news/2026-04-tesla-robotaxi-production-cybercab-ramp.html","source":"TechXplore","thumb":None,"summary":"テキサス州知事がSB2807に署名。ハンドル・ブレーキペダルなし車両の公道走行を正式許可しTesla Cybercab量産に直結。","entities":{"companies":["Tesla"],"countries":["米国"],"services":["Cybercab"],"people":[],"tickers":["TSLA"]},"topics":["自動運転","規制"],"industries":["モビリティ","自動運転"],"events":["規制公表"],"tags":["co/Tesla","country/米国","ticker/TSLA","topic/自動運転","industry/モビリティ","event/規制公表","score/高"]},
    {"genre":"Mobility","score":86,"title":"中国当局、Baidu Apollo Go事故後に自動運転ライセンスを一時停止","url":"https://insideevs.com/news/category/autonomous-vehicles/","source":"InsideEVs","thumb":"https://cdn.motor1.com/custom/share/inside_evs_loadimage.png","summary":"Baidu Apollo Goのロボタクシーが武漢で事故を複数発生させ、中国当局が新規自動運転ライセンスの発行を一時停止。","entities":{"companies":["Baidu"],"countries":["中国"],"services":["Apollo-Go"],"people":[],"tickers":["BIDU"]},"topics":["自動運転","規制"],"industries":["自動運転","モビリティ"],"events":["規制公表"],"tags":["co/Baidu","country/中国","ticker/BIDU","topic/自動運転","industry/モビリティ","event/規制公表","score/高"]},
    {"genre":"Mobility","score":85,"title":"Tesla Cybercabフリートがダラスで拡大 — 12都市以上・専用フリートセンター建設中","url":"https://www.basenor.com/blogs/news/tesla-cybercab-fleet-growing-in-dallas-as-robotaxi-launch-nears","source":"Basenor","thumb":"https://www.basenor.com/cdn/shop/articles/09bff6b053462291c951d8b4cd4fe4dd.jpg?v=1779909175","summary":"TeslaがダラスにCybercabを増車中。テキサス州内12都市以上に拡大済みで専用フリートセンター建設計画も進行。","entities":{"companies":["Tesla"],"countries":["米国"],"services":["Cybercab"],"people":["Elon Musk"],"tickers":["TSLA"]},"topics":["Robotaxi"],"industries":["モビリティ","自動運転"],"events":[],"tags":["co/Tesla","country/米国","ticker/TSLA","topic/Robotaxi","industry/モビリティ","score/高"]},
    # Economy
    {"genre":"Economy","score":92,"title":"S&P 500・NasdaqがAIけん引で最高値更新 — Snowflake 36%急騰","url":"https://www.cnbc.com/2026/05/27/stock-market-today-live-updates.html","source":"CNBC","thumb":"https://image.cnbcfm.com/api/v1/image/108313253-1779982389070-Traders-Photo-20260528-KK-PRESS-005.jpg?v=1779982579&w=1920&h=1080","summary":"5月28日のS&P500は0.58%高の7,563ptと最高値更新。SnowflakeがQ2ガイダンス好調で36.5%急騰。","entities":{"companies":["Snowflake","GoldmanSachs","Microsoft","Palantir"],"countries":["米国"],"services":[],"people":[],"tickers":["SPX","SNOW","MSFT"]},"topics":["株価"],"industries":["金融"],"events":[],"tags":["co/Snowflake","co/GoldmanSachs","country/米国","ticker/SNOW","topic/株価","industry/金融","score/高"]},
    {"genre":"Economy","score":91,"title":"米インフレ率2026年4月3.8%に加速 — 2023年5月以来の高水準","url":"https://tradingeconomics.com/united-states/inflation-cpi","source":"Trading Economics","thumb":None,"summary":"米国の年間インフレ率が2026年4月に3.8%へ上昇し2023年5月以来の最高水準を記録。エネルギー価格上昇が主因。","entities":{"companies":[],"countries":["米国"],"services":[],"people":[],"tickers":[]},"topics":["CPI","インフレ"],"industries":["金融"],"events":["経済指標"],"tags":["country/米国","topic/CPI","industry/金融","event/経済指標","score/高"]},
    {"genre":"Economy","score":90,"title":"日経平均終値306円安 — 「5月売り」観測とSBG続落で一時1000円超安","url":"https://www.nikkei.com/article/DGXZQOUB278GHTX20C26A5000000/","source":"日本経済新聞","thumb":"https://article-image-ix.nikkei.com/https%3A%2F%2Fimgix-proxy.n8s.jp%2FDSXZQO3085847028052026000000-2.jpg?auto=compress&bg=FFFF&crop=focalpoint&fit=crop&fm=jpg&h=630&upscale=false&w=1200&s=960ab8acca47e2bf9e4a589df858e532","summary":"5月28日の日経平均は306円安の64,693円で引け。5月売りとソフトバンクG続落で一時1000円超安を記録。","entities":{"companies":["ソフトバンクG"],"countries":["日本"],"services":[],"people":[],"tickers":["NI225","9984"]},"topics":["株価"],"industries":["金融"],"events":[],"tags":["co/ソフトバンクG","country/日本","ticker/NI225","topic/株価","industry/金融","score/高"]},
    {"genre":"Economy","score":88,"title":"Goldman Sachs、S&P 500年末目標を8,000に引き上げ — AI EPS40%牽引","url":"https://www.cnbc.com/2026/05/27/goldman-raises-its-sp-500-year-end-forecast-its-for-one-simple-reason.html","source":"CNBC","thumb":"https://image.cnbcfm.com/api/v1/image/108235929-1764773476430-gettyimages-2249102764-AFP_86YD9M4.jpeg?v=1779891901&w=1920&h=1080","summary":"Goldman SachsがS&P500の年末目標を7,600から8,000に上方修正。AI関連投資がEPS成長の約40%を牽引するとした。","entities":{"companies":["GoldmanSachs"],"countries":["米国"],"services":[],"people":[],"tickers":["SPX","GS"]},"topics":["株価"],"industries":["金融"],"events":[],"tags":["co/GoldmanSachs","country/米国","ticker/GS","topic/株価","industry/金融","score/高"]},
    {"genre":"Economy","score":88,"title":"日本2026年1〜3月期GDP 実質年率+2.1% — 2四半期連続プラス成長","url":"https://media.monex.co.jp/articles/amp/29387","source":"マネクリ（マネックス証券）","thumb":"https://media.monex.co.jp/mwimgs/c/3/-/img_c392ac838e0894ef5371a4811d7010bc226832.png","summary":"2026年1〜3月期の日本の実質GDP成長率は前期比年率+2.1%と2四半期連続のプラス成長を記録。","entities":{"companies":[],"countries":["日本"],"services":[],"people":[],"tickers":[]},"topics":["GDP"],"industries":["金融"],"events":["経済指標"],"tags":["country/日本","topic/GDP","industry/金融","event/経済指標","score/高"]},
    # Game
    {"genre":"Game","score":90,"title":"Forza Horizon 6、正式リリース後Steam最高同接30万人超 — シリーズ史上最大ローンチ","url":"https://www.gamespark.jp/article/2026/05/19/166588.html","source":"Game*Spark","thumb":"https://www.gamespark.jp/imgs/ogp_f/1130232.jpg","summary":"Forza Horizon 6が正式リリース。Steam最高同接302,645人で前作比約3倍、メタスコアも今年暫定トップを獲得。","entities":{"companies":["Microsoft"],"countries":["日本","米国"],"services":["Forza-Horizon-6"],"people":[],"tickers":["MSFT"]},"topics":["ゲームリリース"],"industries":["ゲーム"],"events":["製品発表"],"tags":["co/Microsoft","country/日本","country/米国","svc/Forza-Horizon-6","topic/ゲームリリース","industry/ゲーム","event/製品発表","score/高"]},
    {"genre":"Game","score":88,"title":"スクウェア・エニックス、賞金総額10億円のゲーム開発コンテスト「SQUARE ENIX GAME CONTEST 2026」発表","url":"https://automaton-media.com/articles/newsjp/20260520-444097/","source":"AUTOMATON","thumb":"https://automaton-media.com/wp-content/uploads/2026/05/20260520-444097-header.jpg","summary":"スクウェア・エニックスが賞金総額10億円のゲーム開発コンテストを発表。最優秀賞3億円で受賞作を全面パブリッシング。","entities":{"companies":["スクウェア・エニックス"],"countries":["日本"],"services":[],"people":[],"tickers":["9684"]},"topics":["ゲーム業界"],"industries":["ゲーム"],"events":["コンテスト"],"tags":["co/スクウェア・エニックス","country/日本","ticker/9684","topic/ゲーム業界","industry/ゲーム","event/コンテスト","score/高"]},
    {"genre":"Game","score":85,"title":"PlayStation「Days of Play 2026」が5月27日スタート — PS5最大1万円引き","url":"https://blog.ja.playstation.com/2026/05/27/20260527-ps5-daysofplay-retail-psstore-sale-s/","source":"PlayStation Blog Japan","thumb":"https://blog.ja.playstation.com/tachyon/sites/7/2026/05/53f99ea06acc65275619ffe0caea34d0a1d37c3e.jpg","summary":"SIEのDays of Play 2026が5月27日〜6月10日開催。PS5ハード最大1万円引きと数百タイトルのセールを実施。","entities":{"companies":["SIE"],"countries":["日本"],"services":["PlayStation-5"],"people":[],"tickers":["6758"]},"topics":["ゲームセール"],"industries":["ゲーム"],"events":["セール"],"tags":["co/SIE","country/日本","ticker/6758","svc/PlayStation-5","topic/ゲームセール","industry/ゲーム","event/セール","score/高"]},
    {"genre":"Game","score":80,"title":"Cygames、3DCG/VFXスタジオ「Griot Groove」を買収 — 映像制作の内製化を加速","url":"https://www.animenewsnetwork.com/news/2026-05-04/cygames-acquires-3dcg-vfx-studio-griot-groove/.237077","source":"Anime News Network","thumb":"https://www.animenewsnetwork.com/thumbnails/crop600x315gIH/cms/news.9/237077/b9f664f9838beac022960c423c023ad2-1024x538.webp","summary":"Cygamesが1996年創業の3DCG・モーションキャプチャスタジオGriot Grooveを完全子会社化。映像品質強化が狙い。","entities":{"companies":["Cygames"],"countries":["日本"],"services":[],"people":[],"tickers":[]},"topics":["ゲーム業界","M&A"],"industries":["ゲーム"],"events":["M&A"],"tags":["co/Cygames","country/日本","topic/M&A","industry/ゲーム","event/M&A","score/中"]},
    {"genre":"Game","score":82,"title":"任天堂、Switch 2向け5月リリース9タイトルを確認 — サードパーティも複数参入","url":"https://www.nintendolife.com/news/2026/05/nintendo-highlights-multiple-major-third-party-releases-for-switch-2-in-2026","source":"Nintendo Life","thumb":"https://images.nintendolife.com/fbba51e86a081/large.jpg","summary":"任天堂が2026年5月にSwitch 2とSwitch向け9作品の発売を公式確認。Indiana Jones and the Great Circleが目玉。","entities":{"companies":["任天堂"],"countries":["日本"],"services":["Switch-2"],"people":[],"tickers":["7974"]},"topics":["ゲームリリース"],"industries":["ゲーム"],"events":["製品発表"],"tags":["co/任天堂","country/日本","ticker/7974","svc/Switch-2","topic/ゲームリリース","industry/ゲーム","event/製品発表","score/中"]},
]

SEEN_AT = "2026-05-29T06:00:00+09:00"
DATE = "2026-05-29"

path = r"C:\Users\hidek\Obsidian\New's Grasp\News-Grasp\data\articles.jsonl"
lines = []
for art in ARTICLES:
    record = {
        "date": DATE, "seen_at": SEEN_AT, "genre": art["genre"],
        "title": art["title"], "url": art["url"],
        "url_norm": normalize_url(art["url"]),
        "source": art["source"], "summary": art["summary"],
        "thumb": art["thumb"],
        "entities": art["entities"], "topics": art["topics"],
        "industries": art["industries"], "events": art["events"],
        "tags": art["tags"],
    }
    lines.append(json.dumps(record, ensure_ascii=False))

with open(path, "a", encoding="utf-8") as f:
    f.write("\n")
    f.write("\n".join(lines))
    f.write("\n")

print(f"Appended {len(lines)} articles to articles.jsonl")
