"""2026-05-25 daily digest を articles.jsonl に追記するスクリプト"""
import json, urllib.parse, os

SEEN_AT = "2026-05-25T06:00:00+09:00"
DATE = "2026-05-25"

def norm_url(url):
    p = urllib.parse.urlparse(url.lower())
    q = urllib.parse.parse_qs(p.query)
    for k in list(q.keys()):
        if any(t in k for t in ['utm_','ref','fbclid','gclid','sessionid','mc_eid']):
            del q[k]
    qs = urllib.parse.urlencode(q, doseq=True)
    path = p.path.rstrip('/')
    return f"{p.netloc}{path}" + (f"?{qs}" if qs else "")

articles = [
  # FX
  {"date":DATE,"seen_at":SEEN_AT,"genre":"FX","title":"Warsh新FRB議長、就任初週はタカ派スタンス継続——インフレ3.8%を前に利下げ封印","url":"https://www.cnbc.com/2026/05/22/trump-kevin-warsh-fed-chair-interest-rates.html","source":"CNBC","summary":"ケビン・ウォーシュが5/22にホワイトハウスで就任宣誓。CPI3.8%背景に利下げ拒絶スタンスを初週から明確化。市場は年内利下げ2回→1回以下に修正しドル買い継続。","thumb":"https://image.cnbcfm.com/api/v1/image/108311287-1779466491747-gettyimages-2277688148-rs2_5781_wb3w.jpeg?v=1779466515&w=1920&h=1080","entities":{"companies":["FRB"],"countries":["米国"],"services":[],"people":["ケビン・ウォーシュ","ドナルド・トランプ"],"tickers":["USDJPY"]},"topics":["FRB","金融政策"],"industries":["金融"],"events":["就任式"],"tags":["cat/fx","co/FRB","country/米国","person/ケビン・ウォーシュ","ticker/USDJPY","topic/FRB","industry/金融","event/就任式","score/高"]},
  {"date":DATE,"seen_at":SEEN_AT,"genre":"FX","title":"ドル円159円台・円安圧力鮮明——BOJがタカ派シグナルを出しても円は戻せない構造","url":"https://www.ig.com/jp/news-and-trade-ideas/jpy-stays-weak-even-after-boj-show-off-hawkish-messages-260428","source":"IG証券","summary":"植田和男総裁が利上げ意欲を示してもドル円が159円台を維持。コアCPIが4年ぶり低水準で日米金利差縮小速度より米側の利下げなしが支配的。介入ライン160円が最重要節目。","thumb":"https://a.c-dn.net/c/content/dam/publicsites/igcom/uk/images/news-article-image-folder/bb_USDJPY_Japan_flag_14_11_2024.jpg/jcr:content/renditions/cq5dam.web.1280.1280.jpeg","entities":{"companies":[],"countries":["日本","米国"],"services":[],"people":["植田和男"],"tickers":["USDJPY"]},"topics":["円安","BOJ"],"industries":["金融"],"events":[],"tags":["cat/fx","country/日本","country/米国","person/植田和男","ticker/USDJPY","topic/円安","industry/金融","score/高"]},
  {"date":DATE,"seen_at":SEEN_AT,"genre":"FX","title":"BOJ 6月利上げ観測——コアCPI鈍化でも引き締めサイクル継続の根拠とリスク","url":"https://www.marketpulse.com/markets/boj-meeting-preview-balancing-act-between-growth-and-inflation-as-usdjpy-approaches-1594516195-key-intervention-risk-zone/","source":"MarketPulse OANDA","summary":"BOJ 6月会合（6/19）に向けた利上げ確率は約55%。USD/JPY 159.45〜161.95円が介入リスクゾーン。MOFは4/30〜5/1で30B超の介入実績。","thumb":"https://storage.googleapis.com/web-content.oanda.com/images/Bank_of_Japan-GettyImages-633058538.original.jpg","entities":{"companies":[],"countries":["日本"],"services":[],"people":["植田和男"],"tickers":["USDJPY"]},"topics":["BOJ","利上げ"],"industries":["金融"],"events":["政策会合"],"tags":["cat/fx","country/日本","person/植田和男","ticker/USDJPY","topic/BOJ","industry/金融","event/政策会合","score/高"]},
  {"date":DATE,"seen_at":SEEN_AT,"genre":"FX","title":"MUFG 5月FX月次レポート——ドル高圧力の持続性と円の押し目買い判断分岐点","url":"https://www.mufgresearch.com/fx/monthly-foreign-exchange-outlook-may-2026/","source":"MUFG Research","summary":"MUFGの5月FXレポートはドル高の主因を米国インフレ高止まり+Warsh就任によるFRB独立性への不確実性と分析。短期はドル高継続、中期は円高修正のシナリオ。","thumb":"https://www.mufgresearch.com/media/yutnrx30/shutterstock_122945524.png","entities":{"companies":["MUFG"],"countries":["米国","日本"],"services":[],"people":[],"tickers":["USDJPY","EURUSD"]},"topics":["FX展望","為替"],"industries":["金融"],"events":[],"tags":["cat/fx","co/MUFG","country/米国","country/日本","ticker/USDJPY","ticker/EURUSD","topic/FX展望","industry/金融","score/中"]},
  {"date":DATE,"seen_at":SEEN_AT,"genre":"FX","title":"週間FXカレンダー5/25〜5/30——FOMC議事録・米PCE・日本鉱工業生産が相場の鍵","url":"https://www.forexfactory.com/calendar?month=this","source":"Forex Factory","summary":"5/25はメモリアルデーで米国全休。重要スケジュールは5/28 FOMC議事録、5/29 米GDP改定値、5/30 PCEコア価格指数。日本では5/29に鉱工業生産・小売売上高。","thumb":None,"entities":{"companies":[],"countries":["米国","日本","EU"],"services":[],"people":[],"tickers":["USDJPY","EURUSD"]},"topics":["FOMC","経済指標"],"industries":["金融"],"events":["政策会合"],"tags":["cat/fx","country/米国","country/日本","ticker/USDJPY","topic/FOMC","industry/金融","event/政策会合","score/中"]},
  # AI
  {"date":DATE,"seen_at":SEEN_AT,"genre":"AI","title":"Gemini Spark ベータ開始——Google AI Ultraで眠らないAIアシスタントが5/25週に動き出す","url":"https://techcrunch.com/2026/05/19/google-introduces-gemini-spark-a-24-7-agentic-assistant-with-gmail-integration/","source":"TechCrunch","summary":"Gemini SparkがGoogle I/O（5/19）から1週間後と約束したAI Ultraベータを5/25週に正式開始。Gmail・Docs・Slideと連携したクラウドベース24時間エージェント。Gemini 3.5+Antigravityハーネス採用。","thumb":"https://techcrunch.com/wp-content/uploads/2026/05/spark.jpg?resize=1200,673","entities":{"companies":["Google"],"countries":["米国"],"services":["Gemini-Spark","Gmail"],"people":["サンダー・ピチャイ"],"tickers":["GOOGL"]},"topics":["AIエージェント","生成AI"],"industries":["AI"],"events":["製品発表"],"tags":["cat/ai","co/Google","country/米国","svc/Gemini-Spark","svc/Gmail","person/サンダー・ピチャイ","ticker/GOOGL","topic/AIエージェント","industry/AI","event/製品発表","score/高"]},
  {"date":DATE,"seen_at":SEEN_AT,"genre":"AI","title":"OpenAI DeployCo $4B始動——McKinsey・TPG・Goldman Sachsが支えるAI展開子会社の全容","url":"https://techjournal.org/openai-launches-4-billion-deployment-company","source":"TechJournal","summary":"OpenAIがTPG・Goldman Sachs・Bain Capital・McKinseyら19社から4Bドルを調達しDeployCoを5/11に設立。埋め込みエンジニア型でGPT-5系モデルを基幹システムに連結する垂直統合モデル。","thumb":"https://techjournal.org/wp-content/uploads/2026/05/openai-launches-4-billion-deployment-company.jpg","entities":{"companies":["OpenAI","McKinsey","Goldman Sachs","TPG"],"countries":["米国"],"services":["DeployCo"],"people":[],"tickers":[]},"topics":["AI投資","エンタープライズAI"],"industries":["AI"],"events":[],"tags":["cat/ai","co/OpenAI","co/McKinsey","country/米国","svc/DeployCo","topic/AI投資","industry/AI","score/高"]},
  {"date":DATE,"seen_at":SEEN_AT,"genre":"AI","title":"Anthropic × Goldman × Blackstone $1.5Bジョイントベンチャー——ClaudeがPE傘下1万社に自律エージェントを展開","url":"https://www.cnbc.com/2026/05/04/anthropic-goldman-blackstone-ai-venture.html","source":"CNBC","summary":"AnthropicがGoldman Sachs・Blackstone・H&Fと$1.5BのJVを設立。PEファンド傘下の数千社にClaudeの自律エージェント機能を組み込む。Goldman社内ではClaudeの会計・コンプライアンス自動化パイロットが進行中。","thumb":"https://image.cnbcfm.com/api/v1/image/108269270-1771956501559-gettyimages-2261854833-AFP_98666EE.jpeg?v=1779385068&w=1920&h=1080","entities":{"companies":["Anthropic","Goldman Sachs","Blackstone"],"countries":["米国"],"services":["Claude"],"people":[],"tickers":[]},"topics":["AI投資","金融AI"],"industries":["AI","金融"],"events":[],"tags":["cat/ai","co/Anthropic","co/Goldman Sachs","co/Blackstone","country/米国","svc/Claude","topic/AI投資","industry/AI","industry/金融","score/高"]},
  {"date":DATE,"seen_at":SEEN_AT,"genre":"AI","title":"Cloudflare 1,100人削減——AI内製化600%増が人的コスト問題を顕在化させた構造","url":"https://finance.yahoo.com/sectors/technology/articles/layoffs-accelerate-may-2026-firms-040430218.html","source":"Yahoo Finance","summary":"Cloudflareが全社員の20%（1,100人超）を削減。内部AI活用が3ヶ月で600%増加し、同じアウトプット量を少ない人員で達成できると経営判断。削減対象はサポート・運用・QA系が中心。","thumb":"https://s.yimg.com/ny/api/res/1.2/GDCcuGuvR4Kq30ZvSTcriA--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NzU-/https://media.zenfs.com/en/beincrypto_us_662/31e4e6650e51130faa1cd1500a1876ab","entities":{"companies":["Cloudflare"],"countries":["米国"],"services":[],"people":[],"tickers":["NET"]},"topics":["AIリストラ","雇用"],"industries":["IT"],"events":[],"tags":["cat/ai","co/Cloudflare","country/米国","ticker/NET","topic/AIリストラ","industry/IT","score/高"]},
  {"date":DATE,"seen_at":SEEN_AT,"genre":"AI","title":"Trump政権、AI事前テスト義務化——Google・Microsoft・xAIが規制当局に早期アクセス提供合意","url":"https://www.cnbc.com/2026/05/05/ai-oversight-trump-google-microsoft-xai.html","source":"CNBC","summary":"Trump政権がAIセーフティ大統領令を廃止した一方で主要AIモデルの政府機関への早期アクセス義務を打ち出し。Google・Microsoft・xAIが合意済み。EU AI Actと対照的なファーストアドプター型ガバナンスへ移行。","thumb":"https://image.cnbcfm.com/api/v1/image/108301477-1777896715502-gettyimages-2273875296-rs2_2378.jpeg?v=1778786289&w=1920&h=1080","entities":{"companies":["Google","Microsoft","xAI"],"countries":["米国"],"services":[],"people":["ドナルド・トランプ"],"tickers":[]},"topics":["AI規制","AIガバナンス"],"industries":["AI"],"events":["規制公表"],"tags":["cat/ai","co/Google","co/Microsoft","co/xAI","country/米国","person/ドナルド・トランプ","topic/AI規制","industry/AI","event/規制公表","score/中"]},
  # IT-Consulting
  {"date":DATE,"seen_at":SEEN_AT,"genre":"IT-Consulting","title":"UK郵便局ホライゾン代替——Accentureが富士通を£2.69億で引き継ぐWalk In Take Over","url":"https://www.theregister.com/paas-and-iaas/2026/05/21/years-after-uk-post-office-scandal-broke-accenture-and-oneview-commerce-bag-contract-to-replace-fujitsu/5244243","source":"The Register","summary":"AccentureとOneView CommerceがUK郵便局のHorizonシステム代替案件（£4.1億）を受注。Accenture分は£2.69億で5年間。6/3に正式契約予定。富士通が1996年から構築した冤罪問題の温床システムを稼働させたまま移行するWalk In Take Over。","thumb":"https://image.theregister.com/5244269.jpg?imageId=5244269&x=0&y=0&cropw=100&croph=100&panox=0&panoy=0&panow=100&panoh=100&width=1200&height=683","entities":{"companies":["Accenture","富士通"],"countries":["英国"],"services":["Horizon"],"people":[],"tickers":[]},"topics":["DX","政府IT"],"industries":["IT-コンサル"],"events":[],"tags":["cat/it","co/Accenture","co/富士通","country/英国","svc/Horizon","topic/DX","industry/IT-コンサル","score/高"]},
  {"date":DATE,"seen_at":SEEN_AT,"genre":"IT-Consulting","title":"Accenture、Faculty買収完了——400人のAIエンジニアで決定論的AI実装力を強化","url":"https://newsroom.accenture.com/news/2026/accenture-completes-acquisition-of-faculty","source":"Accenture Newsroom","summary":"AccentureがUK AIスタートアップFacultyの買収を3/16に完了。400人超のデータサイエンティスト・AIエンジニアが統合。FacultyのDECIDEシミュレーション&最適化プロダクトがAccentureクライアント向けに展開される。","thumb":"https://newsroom.accenture.com/default-meta-image.png?width=1200&format=pjpg&optimize=medium","entities":{"companies":["Accenture","Faculty"],"countries":["英国","米国"],"services":[],"people":[],"tickers":[]},"topics":["M&A","AI実装"],"industries":["IT-コンサル"],"events":["M&A"],"tags":["cat/it","co/Accenture","co/Faculty","country/英国","country/米国","topic/M&A","industry/IT-コンサル","event/M&A","score/高"]},
  {"date":DATE,"seen_at":SEEN_AT,"genre":"IT-Consulting","title":"NTT DOCOMO × Accenture、ユニバーサルウォレット——AIドリブン社会に向けたデジタルID基盤を共同展開","url":"https://newsroom.accenture.com/news/2026/ntt-docomo-global-and-accenture-launch-universal-wallet-infrastructure-powering-the-trusted-future-of-a-data-led-ai-driven-digital-society","source":"Accenture Newsroom","summary":"NTTドコモグローバルとAccentureがユニバーサルウォレット基盤を共同ローンチ。AIが情報を読み解き個人の同意に基づいてデジタルIDを横断管理。欧州eID（EUDI Wallet）との互換性を念頭に設計。","thumb":"https://newsroom.accenture.com/default-meta-image.png?width=1200&format=pjpg&optimize=medium","entities":{"companies":["NTTドコモ","Accenture"],"countries":["日本","米国"],"services":[],"people":[],"tickers":[]},"topics":["DX","デジタルID"],"industries":["IT-コンサル","通信"],"events":[],"tags":["cat/it","co/NTTドコモ","co/Accenture","country/日本","country/米国","topic/DX","industry/IT-コンサル","score/高"]},
  {"date":DATE,"seen_at":SEEN_AT,"genre":"IT-Consulting","title":"Accenture、XBOW投資——自律型AIサイバーセキュリティで攻撃的テストを産業として確立","url":"https://newsroom.accenture.com/news/2026/accenture-invests-in-xbow-to-advance-continuous-offensive-security-testing-and-exposure-management","source":"Accenture Newsroom","summary":"AccentureがXBOW（自律型サイバーセキュリティテストプラットフォーム）に戦略投資。AIエージェントが自動で攻撃シナリオを生成・実行し組織の防御網の弱点を先に発見。連続的露出管理をクライアントに提供。","thumb":"https://newsroom.accenture.com/news/2026/media_14b3576a03d2f026b2c290114872c60f871a0fb72.png?width=1200&format=pjpg&optimize=medium","entities":{"companies":["Accenture","XBOW"],"countries":["米国"],"services":[],"people":[],"tickers":[]},"topics":["サイバーセキュリティ","AI投資"],"industries":["IT-コンサル"],"events":[],"tags":["cat/it","co/Accenture","co/XBOW","country/米国","topic/サイバーセキュリティ","industry/IT-コンサル","score/中"]},
  {"date":DATE,"seen_at":SEEN_AT,"genre":"IT-Consulting","title":"IT Consulting市場2026年13.3%成長——AIエージェント需要が$126.79Bへ市場を押し上げる","url":"https://managementconsulted.com/management-consulting-industry-report/","source":"Management Consulted","summary":"2026年のIT Consulting市場規模は$126.79B（前年$111.95Bから13.3%成長）。生成AI導入・エージェント型AI需要が伸長の主因。スケールドインテグレーターが案件の60%超を独占しており寡占化が加速。","thumb":"https://assets.managementconsulted.com/app/uploads/2025/08/04090850/Management-Consulting-Industry-Report.png","entities":{"companies":[],"countries":["米国"],"services":[],"people":[],"tickers":[]},"topics":["IT投資","コンサル業界"],"industries":["IT-コンサル"],"events":[],"tags":["cat/it","country/米国","topic/IT投資","industry/IT-コンサル","score/中"]},
  # Economy
  {"date":DATE,"seen_at":SEEN_AT,"genre":"Economy","title":"日本Q1 GDP年率2.1%——自動車輸出回復と5期連続の個人消費増で市場予想を上回る成長","url":"https://www.cnbc.com/2026/05/19/japan-first-quarter-gdp-economy-inflation-energy.html","source":"CNBC","summary":"2026年1〜3月期GDP速報値は実質前期比+0.5%（年率2.1%成長）。2四半期連続プラス、市場予想1.7%超え。個人消費+0.3%（5期連続）、設備投資+0.3%（2期連続）、外需寄与+0.3%pt。","thumb":"https://image.cnbcfm.com/api/v1/image/108188376-1755681997373-gettyimages-1252632438-AFP_33EE2UE.jpeg?v=1755682695&w=1920&h=1080","entities":{"companies":[],"countries":["日本"],"services":[],"people":[],"tickers":["TOPIX"]},"topics":["GDP","経済指標"],"industries":[],"events":[],"tags":["cat/economy","country/日本","ticker/TOPIX","topic/GDP","score/高"]},
  {"date":DATE,"seen_at":SEEN_AT,"genre":"Economy","title":"日経平均63,339円・SoftBank主導ラリー——AI投資期待と外国人買いが東京を多年来高値に押し上げ","url":"https://www.bbntimes.com/global-economy/nikkei-225-japan-s-benchmark-surges-2-68-to-63-339-as-softbank-roars-and-ai-optimism-sends-tokyo-to-multi-year-highs","source":"BBNTimes","summary":"5/22（金）日経平均は+2.68%・63,339円で引け。SoftBank（9984）が前日比+12%でラリー牽引。外国人投資家が週間948億円超を買い越し。OpenAI・SB EnergyのIPO観測報道が引き金。","thumb":"https://www.bbntimes.com/images/Nikkei_225_-_Japans_Benchmark_Surges_268_to_63339_as_SoftBank_Roars_and_AI_Optimism_Sends_Tokyo_to_Multi-Year_Highs.jpg","entities":{"companies":["SoftBank"],"countries":["日本"],"services":[],"people":[],"tickers":["9984"]},"topics":["日経平均","株価上昇"],"industries":[],"events":[],"tags":["cat/economy","co/SoftBank","country/日本","ticker/9984","topic/日経平均","score/高"]},
  {"date":DATE,"seen_at":SEEN_AT,"genre":"Economy","title":"米国メモリアルデー全休——週前半薄商い・後半はPCEとFOMC議事録が相場の分水嶺に","url":"https://investinglive.com/stock-market-update/us-markets-face-shortened-friday-and-full-monday-closure-for-memorial-day-20260522/","source":"InvestingLive","summary":"5/25はメモリアルデーで米国株式・債券・先物市場が全休。重要スケジュールは5/28 FOMC議事録、5/29 米GDP改定値、5/30 PCEコア価格指数。S&P500はHHI指数過去最高でAI集中リスクが浮上。","thumb":"https://images.investinglive.com/images/USA_id_4a13eb37-c453-4cfa-8845-f18b9f793950_size975.jpg","entities":{"companies":[],"countries":["米国"],"services":[],"people":[],"tickers":["SPX"]},"topics":["FOMC","PCE"],"industries":[],"events":[],"tags":["cat/economy","country/米国","ticker/SPX","topic/FOMC","score/高"]},
  {"date":DATE,"seen_at":SEEN_AT,"genre":"Economy","title":"Warsh体制初週のFRB——CPI3.8%でタカ派継続・年内利下げ2回観測が1回以下に後退","url":"https://www.troweprice.com/personal-investing/resources/insights/global-markets-weekly-update.html","source":"T. Rowe Price","summary":"Warsh新議長の初週はタカ派スタンスの確認週となる見通し。フェデラルファンド金利の市場織り込みで年内利下げ2回観測から1回以下へ急速にシフト。住宅ローン6.51%が実体経済への冷却効果を発揮。","thumb":"https://www.troweprice.com/etc.clientlibs/iinvestor/clientlibs/global-personal-investor/resources/css/images/TRP_OG_Default.png","entities":{"companies":[],"countries":["米国"],"services":[],"people":["ケビン・ウォーシュ"],"tickers":[]},"topics":["FRB","利下げ観測"],"industries":[],"events":[],"tags":["cat/economy","country/米国","person/ケビン・ウォーシュ","topic/FRB","score/中"]},
  {"date":DATE,"seen_at":SEEN_AT,"genre":"Economy","title":"日本10年債1.8%・日米金利差縮小シナリオ——BOJ 6月利上げで実質金利転換点を模索","url":"https://diamond.jp/zai/articles/-/1066989","source":"ダイヤモンドZAI","summary":"日本10年国債利回りが1.8%を超え始め日米金利差縮小シナリオが現実味を帯びてきた。BOJが6月会合で利上げに踏み切れば実質金利がマイナス圏を脱出する転換点となる可能性。5/30 PCEが鍵。","thumb":"https://dfinance.ismcdn.jp/zai/mwimgs/0/1/-/img_0189c3d91eb4e2955d68b595fc6296c873783.jpg","entities":{"companies":[],"countries":["日本","米国"],"services":[],"people":["植田和男"],"tickers":["USDJPY"]},"topics":["日銀","金利差"],"industries":[],"events":["政策会合"],"tags":["cat/economy","country/日本","country/米国","person/植田和男","ticker/USDJPY","topic/日銀","event/政策会合","score/中"]},
]

for a in articles:
    a["url_norm"] = norm_url(a["url"])

base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
jsonl_path = os.path.join(base, "data", "articles.jsonl")
with open(jsonl_path, "a", encoding="utf-8") as f:
    for a in articles:
        f.write(json.dumps(a, ensure_ascii=False) + "\n")

print(f"OK: {len(articles)}件を articles.jsonl に追記しました")
