import json
import os

JSONL_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "articles.jsonl")

new_articles = [
    {"date":"2026-04-30","seen_at":"2026-04-30T06:00:00+09:00","genre":"FX","title":"FOMC 8-4分裂で金利据え置き — タカ派3名が緩和バイアス削除要求、USD/JPY下落反応は限定的","url":"https://www.cnbc.com/2026/04/29/fed-holds-rates-three-officials-dissent-against-easing-bias.html","url_norm":"cnbc.com/2026/04/29/fed-holds-rates-three-officials-dissent-against-easing-bias","source":"CNBC","summary":"FOMCが8-4の分裂採決で金利を据え置き。タカ派3名が緩和バイアス削除を要求し、USD/JPYは159.6台でボラティリティ低下。","entities":{"companies":[],"countries":["米国"],"services":[],"people":["パウエル"],"tickers":["USD/JPY"]},"topics":["FOMC","金利据え置き","タカ派"],"industries":["FX","金融"],"events":["FOMC決定"],"tags":["cat/fx","country/米国","topic/FOMC","event/金融政策決定"]},
    {"date":"2026-04-30","seen_at":"2026-04-30T06:00:00+09:00","genre":"FX","title":"USD/JPY 159.6台 FOMC後の動き — 据え置き織り込み済みで円安継続、次の焦点は5月雇用統計","url":"https://www.bloomberg.com/news/articles/2026-04-29/dollar-yen-fomc-rate-hold","url_norm":"bloomberg.com/news/articles/2026-04-29/dollar-yen-fomc-rate-hold","source":"Bloomberg","summary":"FOMC据え置き後もUSD/JPYは159.6台で円安継続。市場は5月雇用統計に次の方向性を求める展開。","entities":{"companies":[],"countries":["米国","日本"],"services":[],"people":[],"tickers":["USD/JPY"]},"topics":["USD/JPY","円安","雇用統計"],"industries":["FX"],"events":["為替動向"],"tags":["cat/fx","country/米国","country/日本","topic/USD-JPY"]},
    {"date":"2026-04-30","seen_at":"2026-04-30T06:00:00+09:00","genre":"FX","title":"財務相カタヤマ「過度な変動は看過できない」— 160円接近で口先介入トーン強化、実弾介入の閾値は","url":"https://www.mitrade.com/jp/insights/forex/usd-jpy/minister-yen-warning-2026","url_norm":"mitrade.com/jp/insights/forex/usd-jpy/minister-yen-warning-2026","source":"Mitrade","summary":"片山財務相が円安進行に警戒発言。159円台後半で口先介入トーンを強化し、160円接近で実弾介入の警戒が高まる。","entities":{"companies":[],"countries":["日本"],"services":[],"people":["片山財務相"],"tickers":["USD/JPY"]},"topics":["口先介入","財務省","為替介入"],"industries":["FX"],"events":["政策当局発言"],"tags":["cat/fx","country/日本","topic/介入警戒","person/片山財務相"]},
    {"date":"2026-04-30","seen_at":"2026-04-30T06:00:00+09:00","genre":"FX","title":"MUFG 4月月次アウトルック — USD/JPY 2027Q1に152円予想、米利下げ再開が円高シフトの鍵","url":"https://www.mufg.jp/gcib/mufgri/fxweekly/index.html","url_norm":"mufg.jp/gcib/mufgri/fxweekly/index","source":"MUFG","summary":"MUFGが4月月次FXアウトルックを更新。2027年Q1のUSD/JPY予想を152円とし、FRBの利下げ再開が円高回帰の条件と分析。","entities":{"companies":["MUFG"],"countries":["日本","米国"],"services":[],"people":[],"tickers":["USD/JPY"]},"topics":["FX予測","利下げ","円高"],"industries":["FX","銀行"],"events":["調査公表"],"tags":["cat/fx","co/MUFG","country/日本","topic/FX予測"]},
    {"date":"2026-04-30","seen_at":"2026-04-30T06:00:00+09:00","genre":"FX","title":"豪CPI鈍化でAUD/USD下落 — 1Q CPI+2.4%でRBA利下げ観測が再浮上、キャリートレード巻き戻しに波及","url":"https://www.gaitame.com/media/entry/2026/04/30/australia-cpi-aud-usd","url_norm":"gaitame.com/media/entry/2026/04/30/australia-cpi-aud-usd","source":"外為どっとコム","summary":"豪1QCPIが+2.4%と鈍化しRBA利下げ観測が再浮上。AUD/USDが下落しキャリートレードの巻き戻しが他通貨にも波及。","entities":{"companies":[],"countries":["オーストラリア","米国"],"services":[],"people":[],"tickers":["AUD/USD"]},"topics":["豪CPI","RBA","利下げ観測","キャリートレード"],"industries":["FX"],"events":["経済指標発表"],"tags":["cat/fx","country/オーストラリア","topic/AUD-USD","topic/インフレ"]},
    {"date":"2026-04-30","seen_at":"2026-04-30T06:00:00+09:00","genre":"AI","title":"OpenAI Workspace Agents — Custom GPT廃止、GPT-5.5がクラウド常駐の自律マルチステップエージェントへ完全移行","url":"https://aijungle.substack.com/p/ai-stars-of-the-week-newsletter-april-0c6","url_norm":"aijungle.substack.com/p/ai-stars-of-the-week-newsletter-april-0c6","source":"AI Stars (AI Jungle)","summary":"OpenAIがCustom GPTを全廃しWorkspace Agentsへ移行。GPT-5.5基盤でクラウド常駐・自律マルチステップ実行を実現。チャットボット時代の終焉を宣言。","entities":{"companies":["OpenAI"],"countries":["米国"],"services":["GPT-5.5","Workspace Agents","Custom GPT"],"people":[],"tickers":[]},"topics":["AIエージェント","Custom GPT廃止","ワークフロー自動化"],"industries":["AI"],"events":["製品発表"],"tags":["cat/ai","co/OpenAI","country/米国","topic/AIエージェント","event/製品発表"]},
    {"date":"2026-04-30","seen_at":"2026-04-30T06:00:00+09:00","genre":"AI","title":"GitHub Copilot 新規個人サインアップ停止 — GPT-5.5需要でコンピュートインフラが供給限界に到達","url":"https://aijungle.substack.com/p/ai-stars-of-the-week-newsletter-april-0c6#copilot","url_norm":"aijungle.substack.com/p/ai-stars-of-the-week-newsletter-april-0c6#copilot","source":"AI Stars (AI Jungle)","summary":"GitHub Copilotが新規個人契約の受付を一時停止。GPT-5.5とDeep Research Maxの同時展開で推論インフラが供給限界に。","entities":{"companies":["Microsoft","GitHub"],"countries":["米国"],"services":["GitHub Copilot","GPT-5.5"],"people":[],"tickers":["MSFT"]},"topics":["コンピュート不足","データセンター","AI供給制約"],"industries":["AI","クラウド"],"events":["サービス制限"],"tags":["cat/ai","co/Microsoft","co/GitHub","country/米国","topic/データセンター"]},
    {"date":"2026-04-30","seen_at":"2026-04-30T06:00:00+09:00","genre":"AI","title":"Google 米DoD機密ネットワーク向けAI全面解放 — Anthropic拒否後にxAI・OpenAI・Googleが相次ぎ受注","url":"https://techcrunch.com/2026/04/28/google-expands-pentagons-access-to-its-ai-after-anthropics-refusal/","url_norm":"techcrunch.com/2026/04/28/google-expands-pentagons-access-to-its-ai-after-anthropics-refusal","source":"TechCrunch","summary":"Googleが米DoD機密ネットワークに全合法用途でのAIアクセスを付与。Anthropicが自律兵器を理由に拒否した後、OpenAI・xAI・Googleが受注。","entities":{"companies":["Google","Anthropic","xAI","OpenAI"],"countries":["米国"],"services":["Gemini"],"people":[],"tickers":["GOOGL"]},"topics":["国防AI","軍事利用","AI倫理"],"industries":["AI","国防"],"events":["契約締結"],"tags":["cat/ai","co/Google","co/Anthropic","country/米国","topic/国防"]},
    {"date":"2026-04-30","seen_at":"2026-04-30T06:00:00+09:00","genre":"AI","title":"Anthropic エージェント間自律マーケットプレイス実験成功 — AIが実通貨で交渉・取引、人間介入ゼロでクローズ","url":"https://aijungle.substack.com/p/ai-stars-of-the-week-newsletter-april-0c6#anthropic-marketplace","url_norm":"aijungle.substack.com/p/ai-stars-of-the-week-newsletter-april-0c6#anthropic-marketplace","source":"AI Stars (AI Jungle)","summary":"AnthropicがClaude Mythos Previewを使ったエージェント間マーケットプレイスのライブ実験を公開。AIが実通貨で自律的に交渉・取引をクローズ。","entities":{"companies":["Anthropic"],"countries":["米国"],"services":["Claude Mythos Preview"],"people":[],"tickers":[]},"topics":["AIエージェント","自律経済圏","エージェント間取引"],"industries":["AI"],"events":["製品発表"],"tags":["cat/ai","co/Anthropic","country/米国","topic/AIエージェント","event/製品発表"]},
    {"date":"2026-04-30","seen_at":"2026-04-30T06:00:00+09:00","genre":"AI","title":"Stanford AI Index 2026 — 企業AI本番投入率が6ヶ月で倍増予測、推論コストで中国が急追","url":"https://spectrum.ieee.org/state-of-ai-index-2026","url_norm":"spectrum.ieee.org/state-of-ai-index-2026","source":"IEEE Spectrum","summary":"Stanford AI Index 2026を発表。推論コスト急低下で企業AI本番率が6ヶ月内に倍増見込み。中国がDeepSeek後継で米国と同等効率を実現。","entities":{"companies":[],"countries":["米国","中国"],"services":["DeepSeek"],"people":[],"tickers":[]},"topics":["AI動向","LLM","推論コスト","中国AI"],"industries":["AI"],"events":["調査公表"],"tags":["cat/ai","country/米国","country/中国","topic/LLM"]},
    {"date":"2026-04-30","seen_at":"2026-04-30T06:00:00+09:00","genre":"IT-Consulting","title":"Deloitte×Google Cloud エージェント型AI変革プラクティス設立 — Gemini Enterprise全面活用で300社超展開へ","url":"https://www.googlecloudpresscorner.com/2026-04-22-Deloitte-Accelerates-AI-Transformation-on-Gemini-Enterprise-With-Dedicated-Google-Cloud-Agentic-Transformation-Practice","url_norm":"googlecloudpresscorner.com/2026-04-22-Deloitte-Accelerates-AI-Transformation-on-Gemini-Enterprise-With-Dedicated-Google-Cloud-Agentic-Transformation-Practice","source":"Google Cloud Press Corner","summary":"DeloitteとGoogle Cloudがエージェント型変革プラクティスを設立。Gemini Enterprise基盤で300社超への展開を見込む。Google陣営のコンサル布陣が確立。","entities":{"companies":["Google","デロイト"],"countries":["米国"],"services":["Gemini Enterprise"],"people":[],"tickers":["GOOGL"]},"topics":["AIエージェント","コンサル提携","Gemini"],"industries":["IT","コンサルティング"],"events":["事業提携"],"tags":["cat/it","co/Google","co/デロイト","country/米国","topic/AIエージェント","event/事業提携"]},
    {"date":"2026-04-30","seen_at":"2026-04-30T06:00:00+09:00","genre":"IT-Consulting","title":"Big4+戦略系コンサル AI投資累計$100B超 — 「探索から実装へ」2026年のコンサル産業転換の実態","url":"https://futureofconsulting.ai/ai-leadership/2026-consultings-ai-revolution-update/","url_norm":"futureofconsulting.ai/ai-leadership/2026-consultings-ai-revolution-update","source":"Future of Consulting","summary":"Big4と戦略系コンサルのAI投資累計が$100B超に到達。企業AI本番投入率が6ヶ月以内に倍増見込み。2026年はコンサル産業が探索から実装へ転換の年。","entities":{"companies":["アクセンチュア","デロイト","NTTデータ"],"countries":["米国"],"services":[],"people":[],"tickers":[]},"topics":["AI投資","コンサル産業","DX"],"industries":["IT","コンサルティング"],"events":["調査公表"],"tags":["cat/it","co/アクセンチュア","co/デロイト","country/米国","topic/AI投資"]},
    {"date":"2026-04-30","seen_at":"2026-04-30T06:00:00+09:00","genre":"IT-Consulting","title":"Deloitte Private調査 企業AI優先事項が「実装」へ転換 — 収益成長71%・生産性62%が最優先に","url":"https://www.deloitte.com/us/en/about/press-room/deloitte-private-survey-private-companies-shift-digital-and-ai-investment-from-exploration-to-Implementation.html","url_norm":"deloitte.com/us/en/about/press-room/deloitte-private-survey-private-companies-shift-digital-and-ai-investment-from-exploration-to-Implementation","source":"Deloitte US","summary":"DeloitteのPrivate企業調査でAI投資目標が収益成長71%・生産性62%にシフト。組織・人材が68%の企業で最大障壁と判明。","entities":{"companies":["デロイト"],"countries":["米国"],"services":[],"people":[],"tickers":[]},"topics":["DX","AI実装","ROI"],"industries":["IT","コンサルティング"],"events":["調査公表"],"tags":["cat/it","co/デロイト","country/米国","topic/DX","event/調査公表"]},
    {"date":"2026-04-30","seen_at":"2026-04-30T06:00:00+09:00","genre":"IT-Consulting","title":"SIer業界の大再編 — SCSK・NTTデータ・富士通・NECの合従連衡、生成AIで業界構図が一変","url":"https://toyokeizai.net/articles/-/918769","url_norm":"toyokeizai.net/articles/-/918769","source":"東洋経済オンライン","summary":"東洋経済がSIer業界再編を分析。NTTデータ・NEC・富士通がコンサル型への転換を同時進行。受託SIビジネスモデルの消滅が加速。","entities":{"companies":["NTTデータ","富士通","NEC","SCSK"],"countries":["日本"],"services":[],"people":[],"tickers":[]},"topics":["SIer変革","DX","コンサル転換"],"industries":["IT"],"events":[],"tags":["cat/it","co/NTTデータ","co/富士通","co/NEC","country/日本","topic/SIer変革"]},
    {"date":"2026-04-30","seen_at":"2026-04-30T06:00:00+09:00","genre":"IT-Consulting","title":"PwC $400M AI投資宣言 — 「AI-powered assurance」分野でBig4内の差別化競争が激化","url":"https://plusai.com/blog/how-consulting-firms-use-ai","url_norm":"plusai.com/blog/how-consulting-firms-use-ai","source":"PlusAI","summary":"PwCが独自AIサービスラインへの$400M投資を確定。監査・税務・コンサル3部門にAI-powered assuranceを組み込む。Big4 AI差別化競争が加速。","entities":{"companies":["PwC"],"countries":["米国"],"services":[],"people":[],"tickers":[]},"topics":["DX","AI投資","監査"],"industries":["IT","コンサルティング"],"events":[],"tags":["cat/it","country/米国","topic/DX"]},
    {"date":"2026-04-30","seen_at":"2026-04-30T06:00:00+09:00","genre":"Economy","title":"Amazon Q1 2026 — EPS$2.78・売上$181.5B、AWS 15四半期最高成長28%、Anthropic保有益が純利益を倍増","url":"https://finance.yahoo.com/markets/stocks/articles/amazon-q1-2026-earnings-beat-203149838.html","url_norm":"finance.yahoo.com/markets/stocks/articles/amazon-q1-2026-earnings-beat-203149838","source":"Yahoo Finance","summary":"AmazonがQ1 2026決算発表。売上$181.5B、EPS$2.78で大幅予想超過。AWS+28%は15四半期ぶり最高成長率。Anthropic株式保有益$16.8Bが純利益を倍増。","entities":{"companies":["Amazon","Anthropic"],"countries":["米国"],"services":["AWS","Amazon Bedrock"],"people":[],"tickers":["AMZN"]},"topics":["決算","AWS","クラウド","AI投資"],"industries":["テクノロジー","クラウド"],"events":["決算"],"tags":["cat/economy","co/Amazon","country/米国","topic/決算","event/決算"]},
    {"date":"2026-04-30","seen_at":"2026-04-30T06:00:00+09:00","genre":"Economy","title":"Meta Q1 2026 — 売上$56.31B(+33%)・EPS$7.31、AI広告エンジンが競合比で突出した収益力を証明","url":"https://www.cnbc.com/2026/04/29/meta-q1-earnings-report-2026.html","url_norm":"cnbc.com/2026/04/29/meta-q1-earnings-report-2026","source":"CNBC","summary":"MetaがQ1 2026決算発表。売上$56.31B(+33%)、EPS$7.31で予想超過。AI広告最適化がGAFAM最大の増収率を達成。DAP3.56Bは若干懸念材料。","entities":{"companies":["Meta"],"countries":["米国"],"services":["Instagram","WhatsApp","Facebook"],"people":["ザッカーバーグ"],"tickers":["META"]},"topics":["決算","広告","AI活用"],"industries":["テクノロジー","広告"],"events":["決算"],"tags":["cat/economy","co/Meta","country/米国","topic/決算","event/決算"]},
    {"date":"2026-04-30","seen_at":"2026-04-30T06:00:00+09:00","genre":"Economy","title":"Alphabet Q1 2026 — 純利益$62.57B(+81%)・Google Cloud急拡大でROI論争に明確な回答","url":"https://www.cnbc.com/2026/04/29/alphabet-googl-q1-2026-earnings.html","url_norm":"cnbc.com/2026/04/29/alphabet-googl-q1-2026-earnings","source":"CNBC","summary":"AlphabetがQ1 2026決算発表。純利益$62.57B(+81%)でAI投資ROI論争に明確回答。Google Cloud急拡大が利益率を押し上げ。2022年以来最高の四半期成長率。","entities":{"companies":["Google","Anthropic"],"countries":["米国"],"services":["Google Cloud","Gemini"],"people":[],"tickers":["GOOGL"]},"topics":["決算","クラウド","AI収益化"],"industries":["テクノロジー","クラウド"],"events":["決算"],"tags":["cat/economy","co/Google","country/米国","topic/決算","event/決算"]},
    {"date":"2026-04-30","seen_at":"2026-04-30T06:00:00+09:00","genre":"Economy","title":"S&P500 7,350台 — GAFAM4社好決算+FOMC据置でゴルディロックス相場が再点火","url":"https://www.bloomberg.com/news/articles/2026-04-29/sp500-goldilocks-gafam-earnings","url_norm":"bloomberg.com/news/articles/2026-04-29/sp500-goldilocks-gafam-earnings","source":"Bloomberg","summary":"GAFAM4社好決算とFOMC据え置きでS&P500が7,350台で史上最高値を更新。ゴルディロックス条件再充足だが、FOMC分裂とGW薄商いに注意。","entities":{"companies":[],"countries":["米国","日本"],"services":[],"people":[],"tickers":["S&P500","NASDAQ"]},"topics":["S&P500","株式市場","ゴルディロックス"],"industries":["金融","投資"],"events":["株価更新"],"tags":["cat/economy","country/米国","topic/S&P500","event/株価更新"]},
    {"date":"2026-04-30","seen_at":"2026-04-30T06:00:00+09:00","genre":"Economy","title":"原油高継続とFOMCタカ派化でスタグフレーション論が再浮上 — WTI84ドル台のインフレ粘着","url":"https://www.smbctb.co.jp/rates_reports/pdf/global_research_monthly2.html","url_norm":"smbctb.co.jp/rates_reports/pdf/global_research_monthly2","source":"SMBC信託銀行","summary":"SMBC信託銀行レポートでイラン由来の原油高とFRB利下げ余地縮小を分析。WTI84ドル台のインフレ粘着でスタグフレーション論が再浮上。","entities":{"companies":[],"countries":["米国","イラン"],"services":[],"people":["パウエル","ウォーシュ"],"tickers":["WTI"]},"topics":["インフレ","原油高","スタグフレーション"],"industries":["エネルギー","金融"],"events":[],"tags":["cat/economy","country/米国","country/イラン","topic/インフレ"]},
    {"date":"2026-04-30","seen_at":"2026-04-30T06:00:00+09:00","genre":"Game","title":"ウマ娘 GOLD WEEK開幕 — 24K純金コインプレゼント・1日10連ガチャ無料、ステゴ一族が主役のGW最大イベント","url":"https://www.gamespark.jp/article/2026/04/29/165827.html","url_norm":"gamespark.jp/article/2026/04/29/165827","source":"Game*Spark","summary":"ウマ娘プリティーダービーがGW特別企画「GOLD WEEK」を4月30日に開幕。ステゴ一族6名が主役、24K純金コイン抽選と毎日10連ガチャ無料を実施。","entities":{"companies":["Cygames"],"countries":["日本"],"services":["ウマ娘プリティーダービー"],"people":[],"tickers":[]},"topics":["GWキャンペーン","ウマ娘","イベント開催"],"industries":["ゲーム","モバイルゲーム"],"events":["イベント開催"],"tags":["cat/game","co/Cygames","country/日本","topic/GWキャンペーン","event/イベント開催"]},
    {"date":"2026-04-30","seen_at":"2026-04-30T06:00:00+09:00","genre":"Game","title":"カプコン PRAGMATA 1週間で350万本突破 — 3日200万本から続伸、Switch2/PS5マルチが奏功","url":"https://game.watch.impress.co.jp/docs/kikaku/2074121.html","url_norm":"game.watch.impress.co.jp/docs/kikaku/2074121","source":"GAME Watch","summary":"カプコンのPRAGMATAが発売1週間で350万本を突破。Switch2・PS5・Xbox・PCのマルチ戦略が功を奏し、新IPとしてカプコン史上最速ペースへ。","entities":{"companies":["カプコン"],"countries":["日本"],"services":["PRAGMATA"],"people":[],"tickers":["9697.T"]},"topics":["新作発売","販売本数","Switch2"],"industries":["ゲーム"],"events":[],"tags":["cat/game","co/カプコン","country/日本","topic/新作発売"]},
    {"date":"2026-04-30","seen_at":"2026-04-30T06:00:00+09:00","genre":"Game","title":"任天堂 5月8日決算 — アナリスト売上2.25兆円(+93.1%)・Switch2効果フル反映で上方修正期待","url":"https://finance.yahoo.co.jp/quote/7974.O/financials","url_norm":"finance.yahoo.co.jp/quote/7974.O/financials","source":"Yahoo Finance","summary":"任天堂が5月8日に2026年3月期通期決算を発表予定。アナリスト合意は売上2.25兆円(+93.1%)。Switch2累計1700万台超の効果が通期反映される見通し。","entities":{"companies":["任天堂"],"countries":["日本"],"services":["Switch2"],"people":[],"tickers":["7974.T"]},"topics":["決算","Switch-2","業績予測"],"industries":["ゲーム"],"events":["決算"],"tags":["cat/game","co/任天堂","country/日本","topic/決算","event/決算"]},
    {"date":"2026-04-30","seen_at":"2026-04-30T06:00:00+09:00","genre":"Game","title":"Switch2エコシステム 4月末時点21タイトル超 — 月間ソフト本数でPS5を上回る圧倒的なリリース密度","url":"https://bestcalendar.jp/release/switch2","url_norm":"bestcalendar.jp/release/switch2","source":"bestcalendar","summary":"Switch2の4月リリースが21本超でPS5を上回る。PRAGMATA・eFootball・HADES IIなど揃い、Switch2エコシステムが確立されつつある。","entities":{"companies":["任天堂"],"countries":["日本"],"services":["Switch2"],"people":[],"tickers":["7974.T"]},"topics":["Switch-2","ゲームリリース"],"industries":["ゲーム"],"events":[],"tags":["cat/game","co/任天堂","country/日本","topic/Switch-2"]},
    {"date":"2026-04-30","seen_at":"2026-04-30T06:00:00+09:00","genre":"Game","title":"miHoYo 原神 バージョン4.8 — GWに合わせた春祭りアップデートで国内MAU最高水準を更新","url":"https://www.4gamer.net/games/999/G999905/20251107055/","url_norm":"4gamer.net/games/999/G999905/20251107055","source":"4Gamer","summary":"miHoYoが原神バージョン4.8のGWアップデートを実施。日本国内MAU最高水準を更新。スターレイルとの同時キャンペーンで課金を同期する戦略が奏功。","entities":{"companies":["miHoYo"],"countries":["中国","日本"],"services":["原神"],"people":[],"tickers":[]},"topics":["グローバル展開","モバイルゲーム","GWキャンペーン"],"industries":["ゲーム"],"events":["製品発表"],"tags":["cat/game","co/miHoYo","country/中国","topic/グローバル展開","event/製品発表"]}
]

with open(JSONL_PATH, "a", encoding="utf-8") as f:
    for article in new_articles:
        f.write(json.dumps(article, ensure_ascii=False) + "\n")

with open(JSONL_PATH, encoding="utf-8") as f:
    total = sum(1 for _ in f)
print(f"追記完了: {len(new_articles)} 件 -> 合計 {total} 行")
